export type LandingLanguage = 'en' | 'es' | 'de';

type LocalCopy = {
  seo: { title: string; description: string };
  nav: { how: string; audience: string; capabilities: string; pricing: string; signIn: string; create: string; menu: string };
  hero: { eyebrow: string; title: string; body: string; support: string; primary: string; secondary: string; imageAlt: string };
  problem: { eyebrow: string; title: string; body: string; rows: [string, string][] };
  how: { eyebrow: string; title: string; body: string; steps: [string, string][] };
  connected: { eyebrow: string; title: string; body: string; modelLabel: string; modelNote: string; model: string[]; routes: [string, string[]][] };
  audience: { eyebrow: string; title: string; body: string; groups: [string, string][] };
  visibility: { eyebrow: string; title: string; body: string; labels: string[]; values: string[]; demo: string };
  capabilities: { eyebrow: string; title: string; body: string; items: [string, string][] };
  differences: { eyebrow: string; title: string; body: string; items: [string, string][] };
  trust: { eyebrow: string; title: string; body: string; items: [string, string][] };
  pricing: Record<string, string | string[]>;
  faq: { eyebrow: string; title: string; items: [string, string][] };
  final: { title: string; body: string; create: string; signIn: string };
  footer: string;
};

export const landingCopy: Record<LandingLanguage, LocalCopy> = {
  es: {
    seo: { title: 'Home Guide | Operaciones conectadas al lugar donde ocurren', description: 'Home Guide conecta sitios, activos, trabajo, personas, documentos e información operativa para conservar el contexto desde la planificación hasta el resultado.' },
    nav: { how: 'Cómo funciona', audience: 'Para quién es', capabilities: 'Capacidades', pricing: 'Precios', signIn: 'Ingresar', create: 'Crear cuenta', menu: 'Abrir navegación' },
    hero: { eyebrow: 'OPERACIONES CONECTADAS AL LUGAR DONDE OCURREN', title: 'Cada lugar tiene una operación. Home Guide la mantiene conectada.', body: 'Organice sitios, activos, trabajo, personas, documentos y registros en un mismo contexto. Desde lo que existe en un lugar hasta lo que se hizo, quién lo hizo y qué debe ocurrir después.', support: 'Configure Home Guide según su operación. Active únicamente las capacidades que necesita.', primary: 'Crear cuenta', secondary: 'Ver cómo funciona', imageAlt: 'Propiedad y entorno físico donde se coordinan operaciones de campo' },
    problem: { eyebrow: 'EL PROBLEMA', title: 'El trabajo ocurre en lugares reales. La información suele quedar separada de ellos.', body: 'Una fotografía, una tarea, un activo o un documento pueden existir y aun así perder gran parte de su valor operativo cuando no queda claro a qué lugar, trabajo, persona o cliente pertenecen.', rows: [['INFORMACIÓN SIN CONTEXTO', 'Una fotografía, tarea, activo o documento pierde valor operativo cuando no queda claro a qué lugar, cliente o trabajo pertenece.'], ['TRABAJO DIFÍCIL DE RECONSTRUIR', 'Saber qué se hizo, dónde ocurrió, quién lo hizo y qué falta todavía puede exigir consultar distintos registros y personas.'], ['DISTINTAS VERSIONES DE LA MISMA OPERACIÓN', 'Oficina, campo, administración y cliente pueden terminar trabajando con fragmentos distintos de la misma historia.']] },
    how: { eyebrow: 'CÓMO FUNCIONA', title: 'El registro acompaña al trabajo.', body: 'Home Guide conserva el contexto desde que se organiza un sitio hasta que el resultado llega a quien necesita verlo.', steps: [['ESTRUCTURAR', 'Clientes, propiedades o sitios, zonas y activos crean el contexto donde ocurre la operación.'], ['OPERAR', 'Tareas, visitas, mantenimiento, cuidados, turnos y otros flujos ocurren dentro de ese contexto.'], ['REGISTRAR', 'Personas, tiempo, fotografías, documentos, ubicación y cambios dejan una historia operativa.'], ['COMPARTIR', 'Los mismos registros pueden alimentar reportes, manuales, facturación, portales y seguimiento según la configuración.']] },
    connected: { eyebrow: 'DATOS CONECTADOS', title: 'Un registro, múltiples usos.', body: 'La información capturada durante el trabajo queda disponible para los demás procesos que la necesitan. El contexto no tiene que reconstruirse cada vez.', modelLabel: 'Modelo operativo conectado', modelNote: 'Cada relación se utiliza cuando aplica. Una operación puede comenzar en un sitio y sus registros pueden vincularse al nivel correspondiente.', model: ['Cliente / propietario', 'Sitio / propiedad', 'Zona', 'Activo', 'Trabajo', 'Persona', 'Evidencia'], routes: [['Propiedad / sitio', ['Zonas', 'Activos', 'Tareas', 'Documentos']], ['Tarea / visita', ['Responsable', 'Hora', 'Ubicación', 'Evidencia']], ['Activo', ['Condición', 'Mantenimiento', 'Documentos', 'Historial']], ['Trabajo completado', ['Registro', 'Reporte', 'Portal del cliente', 'Seguimiento']]] },
    audience: { eyebrow: 'CONFIGURACIONES OPERATIVAS', title: 'Un mismo sistema. Distintas operaciones.', body: 'Estos son ejemplos de configuración sobre un mismo modelo operativo, no industrias exclusivas.', groups: [['Servicios y mantenimiento de propiedades', 'Coordine sitios, activos, tareas, mantenimiento, documentación y trabajo recurrente.'], ['Operaciones de campo', 'Coordine asignaciones, visitas, herramientas, horas, personal y comprobación del trabajo.'], ['Servicio de activos y equipos', 'Registre equipos, ubicación, condición, mantenimiento e historial.'], ['Paisajismo y áreas verdes', 'Organice propiedades, zonas, visitas, tareas, equipos y registros de campo.'], ['Administración de propiedades', 'Mantenga propiedades, tareas, documentos, recordatorios y servicios bajo un mismo contexto.'], ['Servicios de plantas e interiorismo vegetal', 'Gestione ubicaciones, plantas, cuidados, visitas, reemplazos y, cuando corresponda, alquileres.'], ['Operación propia', 'Administre sus propiedades, activos, documentos y mantenimiento sin depender de un modelo de clientes.'], ['Configuración personalizada', 'Active los módulos que correspondan cuando su flujo no coincida con una configuración predefinida.']] },
    visibility: { eyebrow: 'VISIBILIDAD OPERATIVA', title: 'El contexto permanece visible.', body: 'En lugar de ver registros aislados, Home Guide permite entender cómo se relacionan el sitio, el activo, el trabajo, la persona responsable y la información disponible.', labels: ['Cliente / propietario', 'Sitio', 'Zona', 'Activo', 'Trabajo', 'Responsable', 'Estado', 'Última evidencia', 'Próxima acción', 'Visibilidad del cliente', 'Documentos relacionados'], values: ['Registro general', 'Sitio operativo', 'Zona de servicio', 'Activo registrado', 'Inspección programada', 'Equipo asignado', 'En revisión', 'Fotografía y check-in', 'Confirmar seguimiento', 'Pendiente de compartir', 'Manual y orden de trabajo'], demo: 'Representación del modelo operativo' },
    capabilities: { eyebrow: 'CAPACIDADES', title: 'Active las capacidades que corresponden a su operación.', body: 'Las herramientas comparten el mismo contexto, pero cada organización decide qué necesita.', items: [['LUGARES Y CONTEXTO', 'Clientes o propietarios, sitios, mapas, zonas, activos, GPS e importación KML/KMZ.'], ['TRABAJO', 'Tareas, visitas, mantenimiento, rutinas de cuidado y recordatorios.'], ['PERSONAS Y RECURSOS', 'Equipos, turnos, horas, tarifas, herramientas e inventario.'], ['REGISTROS Y EVIDENCIA', 'Fotografías, documentos, check-ins, ubicación, historial, reportes y manuales.'], ['ENTREGA AL CLIENTE', 'Portales, reportes, recordatorios, documentos y registros de facturación y pagos.'], ['OPERACIONES ESPECIALIZADAS', 'Plantas, macetas, protocolos de cuidado, alquileres y otros flujos configurables.']] },
    differences: { eyebrow: 'DIFERENCIAS ESTRUCTURALES', title: 'La diferencia está en cómo se conserva el contexto.', body: 'Home Guide conecta las piezas de la operación sin obligar a todos los equipos a trabajar de la misma manera.', items: [['CONTEXTO ESPACIAL', 'El trabajo permanece relacionado con el sitio, zona o activo donde ocurre, cuando ese nivel aplica.'], ['CONTINUIDAD OPERATIVA', 'El registro acompaña al proceso desde la planificación hasta la ejecución y revisión.'], ['EVIDENCIA LIGADA AL TRABAJO', 'Fotografías, tiempo, ubicación y documentos pueden permanecer asociados a la actividad que los produjo.'], ['MODULARIDAD POR OPERACIÓN', 'Cada organización activa las capacidades que necesita sin obligar a todas las operaciones a funcionar igual.'], ['UNA MISMA BASE PARA DISTINTAS VISTAS', 'El mismo contexto puede servir a campo, administración y cliente sin reconstruirse como sistemas separados.'], ['ADAPTACIÓN AL MODELO OPERATIVO', 'Servicios de plantas, paisajismo, propiedades, activos y otras configuraciones extienden el mismo modelo sin convertirse en productos separados.']] },
    trust: { eyebrow: 'CONTROL Y TRAZABILIDAD', title: 'Acceso claro. Registros privados. Historial trazable.', body: 'La información operativa conserva controles de acceso y una historia útil para revisar el trabajo.', items: [['Acceso por rol', 'Dueños, administradores, equipos y otros perfiles ven las herramientas y registros que corresponden a su trabajo.'], ['Registros privados', 'Documentos y fotografías utilizan acceso protegido de acuerdo con la arquitectura actual.'], ['Historial operativo', 'Trabajo, visitas, cuidados, check-ins y otros eventos conservan quién hizo qué y cuándo cuando el flujo correspondiente lo registra.']] },
    pricing: { eyebrow: 'PRECIOS', title: 'Configure la cuenta que su operación necesita.', body: 'Comience con la cantidad de propiedades y active módulos especializados cuando los necesite.', monthly: 'Mensual', annual: 'Anual', annualNote: 'Pague 10 meses, use 12', properties: 'Propiedades', perProperty: 'por propiedad / mes', extras: 'Módulos opcionales', accountMonth: 'cuenta / mes', summary: 'Su estimado', dueMonthly: 'por mes', dueAnnual: 'facturado anualmente', saving: 'Ahorro', continue: 'Crear cuenta y continuar', included: 'Incluido en cada cuenta', includedItems: ['Clientes, propiedades y activos', 'Tareas, evidencia e informes', 'Interfaz EN, ES y DE', 'Visualización USD y CRC'], decrease: 'Reducir propiedades', increase: 'Aumentar propiedades' },
    faq: { eyebrow: 'PREGUNTAS FRECUENTES', title: 'Antes de comenzar', items: [['¿Puedo crear una cuenta ahora?', 'Sí. Cree su cuenta, configure su operación y continúe al proceso de pago.'], ['¿Qué significa la modalidad anual?', 'Recibe doce meses de servicio y se cobra el equivalente a diez meses según la estructura actual de Home Guide.'], ['¿Puedo pagar en dólares o colones?', 'El estimado admite visualización en USD y CRC según la configuración actual.'], ['¿Puedo cambiar mi configuración después?', 'Sí. Puede activar o ajustar capacidades a medida que cambia su operación, sujeto a las reglas actuales de la cuenta.'], ['¿Home Guide es solo para propiedades?', 'No. Home Guide organiza trabajo ligado a sitios físicos y admite distintas configuraciones operativas.'], ['¿Home Guide es un sistema de alquiler de plantas?', 'No. El alquiler es una capacidad opcional utilizada por algunas operaciones. No define el producto.']] },
    final: { title: 'Conserve el contexto de su operación desde el lugar hasta el resultado.', body: 'Organice lo que existe, coordine el trabajo, documente lo ocurrido y mantenga la información disponible para quien la necesita.', create: 'Crear cuenta', signIn: 'Ingresar' },
    footer: 'Operaciones conectadas al lugar donde ocurre el trabajo.',
  },
  en: {
    nav: { how: 'How it works', visibility: 'Visibility', capabilities: 'Capabilities', pricing: 'Pricing', signIn: 'Sign in', create: 'Create account', menu: 'Open navigation' },
    hero: { eyebrow: 'CONNECTED OPERATIONS FOR EVERY PROPERTY', title: 'A living operational record for every property.', body: 'Home Guide connects properties, clients, zones, assets, tasks, visits, plants, people, documents and evidence so the office, field and client work from the same context.', support: 'Activate only the capabilities your operation needs.', primary: 'Create account', secondary: 'See how it works', imageAlt: 'Managed property with landscaped outdoor areas' },
    problem: { eyebrow: 'THE PROBLEM', title: 'The information exists. The problem is rebuilding the operation every time.', body: 'The plan may be in one system, tasks in another, photos in a chat and history with different people. Each piece exists, but it does not always preserve its relationship to the place, asset, responsible person and completed work.', rows: [['Fragmented context', 'Properties, zones, assets, tasks, documents and photographs can exist without sharing one operational structure.'], ['Work without continuity', 'A completed task does not always clearly preserve where it happened, who performed it, which asset it affected and what evidence it left.'], ['Reconstruction for every request', 'When a client, manager or owner needs an answer, the team ends up gathering information it already produced.']] },
    how: { eyebrow: 'HOW IT WORKS', title: 'The record follows the work.', body: 'Home Guide preserves context from the moment a site is organized until the result reaches the client.', steps: [['ORGANIZE', 'Clients, properties, zones and assets form a clear structure. Maps, documents and QR labels keep each record attached to a real place.'], ['EXECUTE', 'Plan tasks, visits, care routines and shifts. Each person sees the work and tools relevant to their role.'], ['DOCUMENT', 'Photography, time, location and logs turn completed work into a verifiable operational record.'], ['SHARE', 'Portals, manuals, reports, reminders and documents turn field records into useful client information.']] },
    connected: { eyebrow: 'CONNECTED DATA', title: 'One record, multiple uses.', body: 'Data captured during work remains available to the other processes that need it. Context does not have to be rebuilt every time.', routes: [['Property', ['Zones', 'Assets', 'Tasks', 'Documents']], ['Task / visit', ['Responsible person', 'Time', 'Location', 'Evidence']], ['Plant / placement', ['Protocol', 'Care', 'History', 'Replacement']], ['Completed work', ['Record', 'Report', 'Client portal', 'Follow-up']]] },
    audience: { eyebrow: 'WHO IT IS FOR', title: 'An operational foundation for teams responsible for real places.', body: 'The structure adapts to each operation while preserving the shared context connecting office, field and client.', groups: [['Property and estate management', 'Coordinate multiple properties, responsible people, documents and work through one consistent record.'], ['Landscape and garden operations', 'Keep tasks, zones, assets and evidence attached to the exact place where work happens.'], ['Plant rental and care teams', 'Connect placements, protocols, visits, care, incidents and replacements.'], ['Facilities and maintenance operations', 'Organize recurring obligations, equipment, shifts and deliverables for every site.']] },
    visibility: { eyebrow: 'OPERATIONAL VISIBILITY', title: 'See the complete context, not an isolated task.', body: 'Each record can bring together place, responsibility, status and evidence to explain what should happen next.', labels: ['Property', 'Zone', 'Assigned work', 'Responsible person', 'Status', 'Latest evidence', 'Next action', 'Client-visible state'], values: ['Property record', 'North garden', 'Irrigation review', 'Field team', 'Under review', 'Photo and work log', 'Confirm follow-up', 'After approval'], demo: 'Operational record representation' },
    capabilities: { eyebrow: 'CAPABILITIES', title: 'Tools that follow the structure of your operation.', body: 'Activate the capabilities you need while keeping everything on the same operational record.', items: [['Mapped sites', 'Satellite maps, drawn zones, located assets and KML/KMZ import.'], ['Tasks and visits', 'Spatial work, calendars, care routines, check-ins and guided visits.'], ['Field evidence', 'Photography, QR, time, location and logs related to the work.'], ['Plant care', 'Profiles, protocols, placements, watering, incidents and replacements.'], ['Labor and tools', 'Shifts, assignments, inventory, checkout and verified returns.'], ['Client delivery', 'Private portals, PDF manuals, reports, reminders, documents and invoicing.']] },
    differences: { eyebrow: 'STRUCTURAL DIFFERENCES', title: 'The value lies in preserving the relationship between every piece.', body: 'Home Guide does not separate execution from its operational context.', items: [['SPATIAL CONTEXT', 'Work remains attached to the property, zone or asset where it happened.'], ['OPERATIONAL CONTINUITY', 'The record follows the process from planning through completion and review.'], ['FIELD EVIDENCE', 'Photo, time, location and related records stay attached to the work.'], ['ROLE-BASED MODULARITY', 'Different teams operate from the same context without seeing irrelevant tools.'], ['CLIENT DELIVERY', 'Records can become reports, manuals and controlled views without rebuilding them separately.']] },
    trust: { eyebrow: 'TRUST', title: 'Clear access. Private records. Traceable history.', body: 'Operational information retains access controls and a useful history for reviewing work.', items: [['Role-based access', 'Owners, managers and crews see the tools and records their work requires.'], ['Private documents and photographs', 'Protected files are delivered through time-limited access.'], ['Traceable history', 'Check-ins, completions and care records preserve who did what and when.']] },
    pricing: { eyebrow: 'PRICING', title: 'Configure the account your operation needs.', body: 'Start with the number of properties and activate specialist modules when you need them.', monthly: 'Monthly', annual: 'Annual', annualNote: 'Pay for 10 months, use 12', properties: 'Properties', perProperty: 'per property / month', extras: 'Optional modules', accountMonth: 'account / month', summary: 'Your estimate', dueMonthly: 'per month', dueAnnual: 'billed annually', saving: 'Saving', continue: 'Create account and continue', included: 'Included in every account', includedItems: ['Clients, properties and assets', 'Tasks, evidence and reports', 'EN, ES and DE interface', 'USD and CRC display'], decrease: 'Decrease properties', increase: 'Increase properties' },
    faq: { eyebrow: 'FREQUENT QUESTIONS', title: 'Before you begin', items: [['Can I create an account now?', 'Yes. Create your account, choose your setup and complete payment with ONVO.'], ['What does annual billing mean?', 'You receive 12 months of service and are charged the equivalent of 10 months.'], ['Can I pay in CRC?', 'Yes. Checkout supports USD and CRC, and the estimate can be viewed in either currency.'], ['Can I change my setup later?', 'Yes. You can add properties and optional modules as your operation changes.']] },
    final: { title: 'Give every property an operational record that continues after the work is done.', body: 'Organize the operation, preserve context and share results from the same system.', create: 'Create account', signIn: 'Sign in' },
    footer: 'Connected operations for property, landscape, plant and facilities teams.',
  },
  de: {
    nav: { how: 'So funktioniert es', visibility: 'Übersicht', capabilities: 'Funktionen', pricing: 'Preise', signIn: 'Anmelden', create: 'Konto erstellen', menu: 'Navigation öffnen' },
    hero: { eyebrow: 'VERNETZTE ABLÄUFE FÜR JEDE IMMOBILIE', title: 'Ein lebendiger Betriebsnachweis für jede Immobilie.', body: 'Home Guide verbindet Immobilien, Kunden, Bereiche, Anlagen, Aufgaben, Besuche, Pflanzen, Personal, Dokumente und Nachweise, damit Büro, Außendienst und Kunde im selben Kontext arbeiten.', support: 'Aktivieren Sie nur die Funktionen, die Ihr Betrieb benötigt.', primary: 'Konto erstellen', secondary: 'So funktioniert es', imageAlt: 'Verwaltete Immobilie mit gestalteten Außenanlagen' },
    problem: { eyebrow: 'DAS PROBLEM', title: 'Die Informationen sind vorhanden. Das Problem ist, den Betrieb jedes Mal neu zusammenzusetzen.', body: 'Der Plan kann in einem System liegen, Aufgaben in einem anderen, Fotos in einem Chat und die Historie bei verschiedenen Personen. Alles ist vorhanden, aber nicht immer mit Ort, Anlage, Verantwortung und ausgeführter Arbeit verbunden.', rows: [['Getrennter Kontext', 'Immobilien, Bereiche, Anlagen, Aufgaben, Dokumente und Fotos können ohne gemeinsame Betriebsstruktur bestehen.'], ['Arbeit ohne Kontinuität', 'Eine erledigte Aufgabe hält nicht immer klar fest, wo sie stattfand, wer sie ausführte, welche Anlage betroffen war und welcher Nachweis entstand.'], ['Neuaufbau bei jeder Anfrage', 'Wenn Kunde, Manager oder Eigentümer eine Antwort benötigt, sammelt das Team bereits erzeugte Informationen erneut.']] },
    how: { eyebrow: 'SO FUNKTIONIERT ES', title: 'Der Datensatz begleitet die Arbeit.', body: 'Home Guide bewahrt den Kontext von der Organisation eines Standorts bis zur Übergabe des Ergebnisses an den Kunden.', steps: [['ORGANISIEREN', 'Kunden, Immobilien, Bereiche und Anlagen bilden eine klare Struktur. Karten, Dokumente und QR-Etiketten verbinden jeden Eintrag mit einem realen Ort.'], ['AUSFÜHREN', 'Planen Sie Aufgaben, Besuche, Pflegeroutinen und Schichten. Jede Person sieht die für ihre Rolle relevanten Arbeiten und Werkzeuge.'], ['DOKUMENTIEREN', 'Fotos, Zeit, Ort und Protokolle machen erledigte Arbeit zu einem überprüfbaren Betriebsnachweis.'], ['TEILEN', 'Portale, Handbücher, Berichte, Erinnerungen und Dokumente machen Felddaten für Kunden nutzbar.']] },
    connected: { eyebrow: 'VERNETZTE DATEN', title: 'Ein Datensatz, viele Nutzungen.', body: 'Während der Arbeit erfasste Daten bleiben für andere Prozesse verfügbar. Der Kontext muss nicht jedes Mal neu aufgebaut werden.', routes: [['Immobilie', ['Bereiche', 'Anlagen', 'Aufgaben', 'Dokumente']], ['Aufgabe / Besuch', ['Verantwortliche Person', 'Zeit', 'Ort', 'Nachweis']], ['Pflanze / Standort', ['Protokoll', 'Pflege', 'Historie', 'Ersatz']], ['Erledigte Arbeit', ['Eintrag', 'Bericht', 'Kundenportal', 'Nachverfolgung']]] },
    audience: { eyebrow: 'FÜR WEN', title: 'Eine Betriebsgrundlage für Teams mit Verantwortung für reale Orte.', body: 'Die Struktur passt sich dem Betrieb an und bewahrt den gemeinsamen Kontext zwischen Büro, Außendienst und Kunde.', groups: [['Immobilien- und Anwesenverwaltung', 'Koordinieren Sie mehrere Immobilien, Verantwortliche, Dokumente und Arbeiten in einem konsistenten Nachweis.'], ['Landschafts- und Gartenbetrieb', 'Verbinden Sie Aufgaben, Bereiche, Anlagen und Nachweise mit dem genauen Arbeitsort.'], ['Pflanzenvermietung und -pflege', 'Verbinden Sie Standorte, Protokolle, Besuche, Pflege, Vorfälle und Ersatz.'], ['Gebäude- und Instandhaltungsbetrieb', 'Organisieren Sie wiederkehrende Pflichten, Geräte, Schichten und Ergebnisse je Standort.']] },
    visibility: { eyebrow: 'BETRIEBSÜBERSICHT', title: 'Sehen Sie den vollständigen Kontext, nicht nur eine einzelne Aufgabe.', body: 'Jeder Eintrag kann Ort, Verantwortung, Status und Nachweis zusammenführen und den nächsten Schritt erklären.', labels: ['Immobilie', 'Bereich', 'Zugewiesene Arbeit', 'Verantwortlich', 'Status', 'Letzter Nachweis', 'Nächster Schritt', 'Für Kunden sichtbar'], values: ['Immobilieneintrag', 'Nordgarten', 'Bewässerung prüfen', 'Außendienstteam', 'In Prüfung', 'Foto und Protokoll', 'Nachverfolgung bestätigen', 'Nach Freigabe'], demo: 'Darstellung eines Betriebsnachweises' },
    capabilities: { eyebrow: 'FUNKTIONEN', title: 'Werkzeuge, die der Struktur Ihres Betriebs folgen.', body: 'Aktivieren Sie benötigte Funktionen und halten Sie alles im selben Betriebsnachweis.', items: [['Kartierte Standorte', 'Satellitenkarten, gezeichnete Bereiche, verortete Anlagen und KML/KMZ-Import.'], ['Aufgaben und Besuche', 'Räumliche Arbeit, Kalender, Pflegeroutinen, Check-ins und geführte Besuche.'], ['Felddokumentation', 'Fotos, QR, Zeit, Ort und Protokolle im Zusammenhang mit der Arbeit.'], ['Pflanzenpflege', 'Profile, Protokolle, Standorte, Bewässerung, Vorfälle und Ersatz.'], ['Personal und Werkzeuge', 'Schichten, Zuweisungen, Bestand, Ausgabe und bestätigte Rückgabe.'], ['Kundenübergabe', 'Private Portale, PDF-Handbücher, Berichte, Erinnerungen, Dokumente und Rechnungen.']] },
    differences: { eyebrow: 'STRUKTURELLE UNTERSCHIEDE', title: 'Der Wert liegt darin, die Beziehung zwischen allen Teilen zu bewahren.', body: 'Home Guide trennt die Ausführung nicht von ihrem betrieblichen Kontext.', items: [['RÄUMLICHER KONTEXT', 'Arbeit bleibt mit der Immobilie, dem Bereich oder der Anlage verbunden, wo sie stattfand.'], ['BETRIEBLICHE KONTINUITÄT', 'Der Datensatz begleitet den Prozess von Planung über Abschluss bis Prüfung.'], ['FELDNACHWEIS', 'Foto, Zeit, Ort und zugehörige Einträge bleiben mit der Arbeit verbunden.'], ['ROLLENBASIERTE MODULARITÄT', 'Teams arbeiten im selben Kontext, ohne irrelevante Werkzeuge zu sehen.'], ['KUNDENÜBERGABE', 'Einträge werden zu Berichten, Handbüchern und kontrollierten Ansichten, ohne sie neu aufzubauen.']] },
    trust: { eyebrow: 'VERTRAUEN', title: 'Klarer Zugriff. Private Einträge. Nachvollziehbare Historie.', body: 'Betriebsinformationen behalten Zugriffskontrollen und eine nützliche Historie zur Prüfung der Arbeit.', items: [['Rollenbasierter Zugriff', 'Eigentümer, Manager und Teams sehen die passenden Werkzeuge und Einträge.'], ['Private Dokumente und Fotos', 'Geschützte Dateien werden über zeitlich begrenzte Zugriffe bereitgestellt.'], ['Nachvollziehbare Historie', 'Check-ins, Abschlüsse und Pflegeeinträge halten fest, wer was wann getan hat.']] },
    pricing: { eyebrow: 'PREISE', title: 'Konfigurieren Sie das Konto, das Ihr Betrieb benötigt.', body: 'Beginnen Sie mit der Anzahl der Immobilien und aktivieren Sie Spezialmodule nach Bedarf.', monthly: 'Monatlich', annual: 'Jährlich', annualNote: '10 Monate zahlen, 12 nutzen', properties: 'Immobilien', perProperty: 'pro Immobilie / Monat', extras: 'Optionale Module', accountMonth: 'Konto / Monat', summary: 'Ihre Schätzung', dueMonthly: 'pro Monat', dueAnnual: 'jährlich berechnet', saving: 'Ersparnis', continue: 'Konto erstellen und fortfahren', included: 'In jedem Konto enthalten', includedItems: ['Kunden, Immobilien und Anlagen', 'Aufgaben, Nachweise und Berichte', 'Oberfläche EN, ES und DE', 'Anzeige in USD und CRC'], decrease: 'Immobilien reduzieren', increase: 'Immobilien erhöhen' },
    faq: { eyebrow: 'HÄUFIGE FRAGEN', title: 'Vor dem Start', items: [['Kann ich jetzt ein Konto erstellen?', 'Ja. Erstellen Sie Ihr Konto, wählen Sie die Konfiguration und schließen Sie die Zahlung mit ONVO ab.'], ['Was bedeutet jährliche Abrechnung?', 'Sie erhalten 12 Monate Service und bezahlen den Gegenwert von 10 Monaten.'], ['Kann ich in CRC bezahlen?', 'Ja. Der Checkout unterstützt USD und CRC; die Schätzung ist in beiden Währungen sichtbar.'], ['Kann ich meine Konfiguration später ändern?', 'Ja. Sie können Immobilien und optionale Module ergänzen, wenn sich Ihr Betrieb verändert.']] },
    final: { title: 'Geben Sie jeder Immobilie einen Betriebsnachweis, der nach Abschluss der Arbeit fortbesteht.', body: 'Organisieren Sie den Betrieb, bewahren Sie den Kontext und teilen Sie Ergebnisse im selben System.', create: 'Konto erstellen', signIn: 'Anmelden' },
    footer: 'Vernetzte Abläufe für Immobilien-, Landschafts-, Pflanzen- und Facility-Teams.',
  },
};
