export type LandingLanguage = 'en' | 'es' | 'de';

type LocalCopy = {
  seo: { title: string; description: string };
  nav: { how: string; audience: string; capabilities: string; pricing: string; signIn: string; create: string; menu: string };
  hero: { eyebrow: string; title: string; body: string; support: string; primary: string; secondary: string; imageAlt: string };
  problem: { eyebrow: string; title: string; body: string; rows: [string, string][] };
  how: { eyebrow: string; title: string; body: string; steps: [string, string][] };
  connected: { eyebrow: string; title: string; body: string; modelLabel: string; modelNote: string; model: string[]; routes: [string, string[]][] };
  audience: { eyebrow: string; title: string; body: string; groups: [string, string][] };
  visibility: { eyebrow: string; title: string; body: string; labels: string[]; values: string[]; demo: string };
  capabilities: { eyebrow: string; title: string; body: string; items: [string, string][] };
  differences: { eyebrow: string; title: string; body: string; items: [string, string][] };
  trust: { eyebrow: string; title: string; body: string; items: [string, string][] };
  pricing: Record<string, string | string[]>;
  faq: { eyebrow: string; title: string; items: [string, string][] };
  final: { title: string; body: string; create: string; signIn: string };
  footer: string;
};

export const landingCopy: Record<LandingLanguage, LocalCopy> = {
  es: {
    seo: { title: 'Home Guide | Operaciones conectadas al lugar donde ocurren', description: 'Home Guide conecta sitios, activos, trabajo, personas, documentos e información operativa para conservar el contexto desde la planificación hasta el resultado.' },
    nav: { how: 'Cómo funciona', audience: 'Para quién es', capabilities: 'Capacidades', pricing: 'Precios', signIn: 'Ingresar', create: 'Crear cuenta', menu: 'Abrir navegación' },
    hero: { eyebrow: 'OPERACIONES CONECTADAS AL LUGAR DONDE OCURREN', title: 'Cada lugar tiene una operación. Home Guide la mantiene conectada.', body: 'Organice sitios, activos, trabajo, personas, documentos y registros en un mismo contexto. Desde lo que existe en un lugar hasta lo que se hizo, quién lo hizo y qué debe ocurrir después.', support: 'Configure Home Guide según su operación. Active únicamente las capacidades que necesita.', primary: 'Crear cuenta', secondary: 'Ver cómo funciona', imageAlt: 'Propiedad y entorno físico donde se coordinan operaciones de campo' },
    problem: { eyebrow: 'EL PROBLEMA', title: 'El trabajo ocurre en lugares reales. La información suele quedar separada de ellos.', body: 'Una fotografía, una tarea, un activo o un documento pueden existir y aun así perder gran parte de su valor operativo cuando no queda claro a qué lugar, trabajo, persona o cliente pertenecen.', rows: [['INFORMACIÓN SIN CONTEXTO', 'Una fotografía, tarea, activo o documento pierde valor operativo cuando no queda claro a qué lugar, cliente o trabajo pertenece.'], ['TRABAJO DIFÍCIL DE RECONSTRUIR', 'Saber qué se hizo, dónde ocurrió, quién lo hizo y qué falta todavía puede exigir consultar distintos registros y personas.'], ['DISTINTAS VERSIONES DE LA MISMA OPERACIÓN', 'Oficina, campo, administración y cliente pueden terminar trabajando con fragmentos distintos de la misma historia.']] },
    how: { eyebrow: 'CÓMO FUNCIONA', title: 'El registro acompaña al trabajo.', body: 'Home Guide conserva el contexto desde que se organiza un sitio hasta que el resultado llega a quien necesita verlo.', steps: [['ESTRUCTURAR', 'Clientes, propiedades o sitios, zonas y activos crean el contexto donde ocurre la operación.'], ['OPERAR', 'Tareas, visitas, mantenimiento, cuidados, turnos y otros flujos ocurren dentro de ese contexto.'], ['REGISTRAR', 'Personas, tiempo, fotografías, documentos, ubicación y cambios dejan una historia operativa.'], ['COMPARTIR', 'Los mismos registros pueden alimentar reportes, manuales, facturación, portales y seguimiento según la configuración.']] },
    connected: { eyebrow: 'DATOS CONECTADOS', title: 'Un registro, múltiples usos.', body: 'La información capturada durante el trabajo queda disponible para los demás procesos que la necesitan. El contexto no tiene que reconstruirse cada vez.', modelLabel: 'Modelo operativo conectado', modelNote: 'Cada relación se utiliza cuando aplica. Una operación puede comenzar en un sitio y sus registros pueden vincularse al nivel correspondiente.', model: ['Cliente / propietario', 'Sitio / propiedad', 'Zona', 'Activo', 'Trabajo', 'Persona', 'Evidencia'], routes: [['Propiedad / sitio', ['Zonas', 'Activos', 'Tareas', 'Documentos']], ['Tarea / visita', ['Responsable', 'Hora', 'Ubicación', 'Evidencia']], ['Activo', ['Condición', 'Mantenimiento', 'Documentos', 'Historial']], ['Trabajo completado', ['Registro', 'Reporte', 'Portal del cliente', 'Seguimiento']]] },
    audience: { eyebrow: 'CONFIGURACIONES OPERATIVAS', title: 'Un mismo sistema. Distintas operaciones.', body: 'Estos son ejemplos de configuración sobre un mismo modelo operativo, no industrias exclusivas.', groups: [['Servicios y mantenimiento de propiedades', 'Coordine sitios, activos, tareas, mantenimiento, documentación y trabajo recurrente.'], ['Operaciones de campo', 'Coordine asignaciones, visitas, herramientas, horas, personal y comprobación del trabajo.'], ['Servicio de activos y equipos', 'Registre equipos, ubicación, condición, mantenimiento e historial.'], ['Paisajismo y áreas verdes', 'Organice propiedades, zonas, visitas, tareas, equipos y registros de campo.'], ['Administración de propiedades', 'Mantenga propiedades, tareas, documentos, recordatorios y servicios bajo un mismo contexto.'], ['Servicios de plantas e interiorismo vegetal', 'Gestione ubicaciones, plantas, cuidados, visitas, reemplazos y, cuando corresponda, alquileres.'], ['Operación propia', 'Administre sus propiedades, activos, documentos y mantenimiento sin depender de un modelo de clientes.'], ['Configuración personalizada', 'Active los módulos que correspondan cuando su flujo no coincida con una configuración predefinida.']] },
    visibility: { eyebrow: 'VISIBILIDAD OPERATIVA', title: 'El contexto permanece visible.', body: 'En lugar de ver registros aislados, Home Guide permite entender cómo se relacionan el sitio, el activo, el trabajo, la persona responsable y la información disponible.', labels: ['Cliente / propietario', 'Sitio', 'Zona', 'Activo', 'Trabajo', 'Responsable', 'Estado', 'Última evidencia', 'Próxima acción', 'Visibilidad del cliente', 'Documentos relacionados'], values: ['Registro general', 'Sitio operativo', 'Zona de servicio', 'Activo registrado', 'Inspección programada', 'Equipo asignado', 'En revisión', 'Fotografía y check-in', 'Confirmar seguimiento', 'Pendiente de compartir', 'Manual y orden de trabajo'], demo: 'Representación del modelo operativo' },
    capabilities: { eyebrow: 'CAPACIDADES', title: 'Active las capacidades que corresponden a su operación.', body: 'Las herramientas comparten el mismo contexto, pero cada organización decide qué necesita.', items: [['LUGARES Y CONTEXTO', 'Clientes o propietarios, sitios, mapas, zonas, activos, GPS e importación KML/KMZ.'], ['TRABAJO', 'Tareas, visitas, mantenimiento, rutinas de cuidado y recordatorios.'], ['PERSONAS Y RECURSOS', 'Equipos, turnos, horas, tarifas, herramientas e inventario.'], ['REGISTROS Y EVIDENCIA', 'Fotografías, documentos, check-ins, ubicación, historial, reportes y manuales.'], ['ENTREGA AL CLIENTE', 'Portales, reportes, recordatorios, documentos y registros de facturación y pagos.'], ['OPERACIONES ESPECIALIZADAS', 'Plantas, macetas, protocolos de cuidado, alquileres y otros flujos configurables.']] },
    differences: { eyebrow: 'DIFERENCIAS ESTRUCTURALES', title: 'La diferencia está en cómo se conserva el contexto.', body: 'Home Guide conecta las piezas de la operación sin obligar a todos los equipos a trabajar de la misma manera.', items: [['CONTEXTO ESPACIAL', 'El trabajo permanece relacionado con el sitio, zona o activo donde ocurre, cuando ese nivel aplica.'], ['CONTINUIDAD OPERATIVA', 'El registro acompaña al proceso desde la planificación hasta la ejecución y revisión.'], ['EVIDENCIA LIGADA AL TRABAJO', 'Fotografías, tiempo, ubicación y documentos pueden permanecer asociados a la actividad que los produjo.'], ['MODULARIDAD POR OPERACIÓN', 'Cada organización activa las capacidades que necesita sin obligar a todas las operaciones a funcionar igual.'], ['UNA MISMA BASE PARA DISTINTAS VISTAS', 'El mismo contexto puede servir a campo, administración y cliente sin reconstruirse como sistemas separados.'], ['ADAPTACIÓN AL MODELO OPERATIVO', 'Servicios de plantas, paisajismo, propiedades, activos y otras configuraciones extienden el mismo modelo sin convertirse en productos separados.']] },
    trust: { eyebrow: 'CONTROL Y TRAZABILIDAD', title: 'Acceso claro. Registros privados. Historial trazable.', body: 'La información operativa conserva controles de acceso y una historia útil para revisar el trabajo.', items: [['Acceso por rol', 'Dueños, administradores, equipos y otros perfiles ven las herramientas y registros que corresponden a su trabajo.'], ['Registros privados', 'Documentos y fotografías utilizan acceso protegido de acuerdo con la arquitectura actual.'], ['Historial operativo', 'Trabajo, visitas, cuidados, check-ins y otros eventos conservan quién hizo qué y cuándo cuando el flujo correspondiente lo registra.']] },
    pricing: { eyebrow: 'PRECIOS', title: 'Configure la cuenta que su operación necesita.', body: 'Comience con la cantidad de propiedades y active módulos especializados cuando los necesite.', monthly: 'Mensual', annual: 'Anual', annualNote: 'Pague 10 meses, use 12', properties: 'Propiedades', perProperty: 'por propiedad / mes', extras: 'Módulos opcionales', accountMonth: 'cuenta / mes', summary: 'Su estimado', dueMonthly: 'por mes', dueAnnual: 'facturado anualmente', saving: 'Ahorro', continue: 'Crear cuenta y continuar', included: 'Incluido en cada cuenta', includedItems: ['Clientes, propiedades y activos', 'Tareas, evidencia e informes', 'Interfaz EN, ES y DE', 'Visualización USD y CRC'], decrease: 'Reducir propiedades', increase: 'Aumentar propiedades' },
    faq: { eyebrow: 'PREGUNTAS FRECUENTES', title: 'Antes de comenzar', items: [['¿Puedo crear una cuenta ahora?', 'Sí. Cree su cuenta, configure su operación y continúe al proceso de pago.'], ['¿Qué significa la modalidad anual?', 'Recibe doce meses de servicio y se cobra el equivalente a diez meses según la estructura actual de Home Guide.'], ['¿Puedo pagar en dólares o colones?', 'El estimado admite visualización en USD y CRC según la configuración actual.'], ['¿Puedo cambiar mi configuración después?', 'Sí. Puede activar o ajustar capacidades a medida que cambia su operación, sujeto a las reglas actuales de la cuenta.'], ['¿Home Guide es solo para propiedades?', 'No. Home Guide organiza trabajo ligado a sitios físicos y admite distintas configuraciones operativas.'], ['¿Home Guide es un sistema de alquiler de plantas?', 'No. El alquiler es una capacidad opcional utilizada por algunas operaciones. No define el producto.']] },
    final: { title: 'Conserve el contexto de su operación desde el lugar hasta el resultado.', body: 'Organice lo que existe, coordine el trabajo, documente lo ocurrido y mantenga la información disponible para quien la necesita.', create: 'Crear cuenta', signIn: 'Ingresar' },
    footer: 'Operaciones conectadas al lugar donde ocurre el trabajo.',
  },
  en: {
    seo: { title: 'Home Guide | Operations connected to the places where work happens', description: 'Home Guide connects sites, assets, work, people, documents and operational records so physical operations keep their context from planning through completion.' },
    nav: { how: 'How it works', audience: "Who it's for", capabilities: 'Capabilities', pricing: 'Pricing', signIn: 'Sign in', create: 'Create account', menu: 'Open navigation' },
    hero: { eyebrow: 'OPERATIONS CONNECTED TO WHERE WORK HAPPENS', title: 'Every place has an operation. Home Guide keeps it connected.', body: 'Organize sites, assets, work, people, documents and records within the same operational context. From what exists in a place to what was done, who did it and what needs to happen next.', support: 'Configure Home Guide around your operation. Enable only the capabilities you need.', primary: 'Create account', secondary: 'See how it works', imageAlt: 'A physical property and environment where field operations take place' },
    problem: { eyebrow: 'THE PROBLEM', title: 'Work happens in physical places. The information often becomes separated from them.', body: 'A photo, task, asset or document can exist and still lose much of its operational value when it is unclear which place, work, person or client it belongs to.', rows: [['INFORMATION WITHOUT CONTEXT', 'A photo, task, asset or document loses operational value when it is unclear which place, client or piece of work it belongs to.'], ['WORK THAT MUST BE RECONSTRUCTED', 'Understanding what happened, where, who did it and what remains open may require checking multiple records and people.'], ['DIFFERENT VERSIONS OF THE SAME OPERATION', 'Office, field teams, management and clients can end up working from different fragments of the same story.']] },
    how: { eyebrow: 'HOW IT WORKS', title: 'The record follows the work.', body: 'Home Guide preserves context from the moment a site is organized until the result reaches the person who needs it.', steps: [['STRUCTURE', 'Clients, properties or sites, zones and assets create the context in which the operation happens.'], ['OPERATE', 'Tasks, visits, maintenance, care routines, shifts and other workflows happen inside that context.'], ['RECORD', 'People, time, photos, documents, location and changes build an operational history.'], ['SHARE', 'The same records can support reports, manuals, billing, portals and follow-up depending on the configuration.']] },
    connected: { eyebrow: 'CONNECTED DATA', title: 'One record, multiple uses.', body: 'Information captured during work remains available to the other processes that need it. Context does not have to be rebuilt every time.', modelLabel: 'Connected operating model', modelNote: 'Each relationship is used when it applies. An operation can begin at a site, and records can connect at the relevant level.', model: ['Client / owner', 'Site / property', 'Zone', 'Asset', 'Work', 'Person', 'Evidence'], routes: [['Property / site', ['Zones', 'Assets', 'Tasks', 'Documents']], ['Task / visit', ['Responsible person', 'Time', 'Location', 'Evidence']], ['Asset', ['Condition', 'Maintenance', 'Documents', 'History']], ['Completed work', ['Record', 'Report', 'Client portal', 'Follow-up']]] },
    audience: { eyebrow: 'OPERATING CONFIGURATIONS', title: 'One system. Different operations.', body: 'These are examples of configurations built on the same operating model, not exclusive industries.', groups: [['Property services and maintenance', 'Coordinate sites, assets, tasks, maintenance, documentation and recurring work.'], ['Field operations', 'Coordinate assignments, visits, tools, hours, people and proof of completed work.'], ['Asset and equipment service', 'Record equipment, location, condition, maintenance and history.'], ['Landscaping and grounds', 'Organize properties, zones, visits, tasks, teams and field records.'], ['Property management', 'Keep properties, tasks, documents, reminders and services in one context.'], ['Plant and interior landscape services', 'Manage placements, plants, care, visits, replacements and rentals when relevant.'], ['Own operation', 'Manage your own properties, assets, documents and maintenance without a client model.'], ['Custom configuration', 'Enable the modules that fit when your workflow does not match a predefined configuration.']] },
    visibility: { eyebrow: 'OPERATIONAL VISIBILITY', title: 'Context remains visible.', body: 'Instead of isolated records, Home Guide shows how the site, asset, work, responsible person and available information relate.', labels: ['Client / owner', 'Site', 'Zone', 'Asset', 'Work', 'Responsible person', 'Status', 'Latest evidence', 'Next action', 'Client visibility', 'Related documents'], values: ['General record', 'Operating site', 'Service zone', 'Registered asset', 'Scheduled inspection', 'Assigned team', 'Under review', 'Photo and check-in', 'Confirm follow-up', 'Pending share', 'Manual and work order'], demo: 'Operating model representation' },
    capabilities: { eyebrow: 'CAPABILITIES', title: 'Enable the capabilities that fit your operation.', body: 'The tools share the same context, while each organization decides what it needs.', items: [['PLACES AND CONTEXT', 'Clients or owners, sites, maps, zones, assets, GPS and KML/KMZ import.'], ['WORK', 'Tasks, visits, maintenance, care routines and reminders.'], ['PEOPLE AND RESOURCES', 'Teams, shifts, hours, rates, tools and inventory.'], ['RECORDS AND EVIDENCE', 'Photos, documents, check-ins, location, history, reports and manuals.'], ['CLIENT DELIVERY', 'Portals, reports, reminders, documents, billing and payment records.'], ['SPECIALIZED OPERATIONS', 'Plants, pots, care protocols, rentals and other configurable workflows.']] },
    differences: { eyebrow: 'STRUCTURAL DIFFERENCES', title: 'The difference is how context is preserved.', body: 'Home Guide connects operational pieces without forcing every team to work in the same way.', items: [['SPATIAL CONTEXT', 'Work remains related to the site, zone or asset where it happens when that level applies.'], ['OPERATIONAL CONTINUITY', 'The record follows the process from planning through execution and review.'], ['EVIDENCE CONNECTED TO WORK', 'Photos, time, location and documents can remain associated with the activity that produced them.'], ['MODULARITY BY OPERATION', 'Each organization enables the capabilities it needs without forcing every operation into the same model.'], ['ONE FOUNDATION FOR DIFFERENT VIEWS', 'The same context can serve field teams, management and clients without becoming separate systems.'], ['ADAPTS TO THE OPERATING MODEL', 'Plant services, landscaping, property services, asset operations and other configurations extend the same model instead of becoming separate products.']] },
    trust: { eyebrow: 'CONTROL AND TRACEABILITY', title: 'Clear access. Private records. Traceable history.', body: 'Operational information retains access controls and a useful history for reviewing work.', items: [['Role-based access', 'Owners, managers, teams and other profiles see the tools and records relevant to their work.'], ['Private records', 'Documents and photographs use protected access within the current architecture.'], ['Operational history', 'Work, visits, care, check-ins and other events preserve who did what and when when the corresponding workflow records it.']] },
    pricing: { eyebrow: 'PRICING', title: 'Configure the account your operation needs.', body: 'Start with the number of properties and activate specialist modules when you need them.', monthly: 'Monthly', annual: 'Annual', annualNote: 'Pay for 10 months, use 12', properties: 'Properties', perProperty: 'per property / month', extras: 'Optional modules', accountMonth: 'account / month', summary: 'Your estimate', dueMonthly: 'per month', dueAnnual: 'billed annually', saving: 'Saving', continue: 'Create account and continue', included: 'Included in every account', includedItems: ['Clients, properties and assets', 'Tasks, evidence and reports', 'EN, ES and DE interface', 'USD and CRC display'], decrease: 'Decrease properties', increase: 'Increase properties' },
    faq: { eyebrow: 'FREQUENT QUESTIONS', title: 'Before you begin', items: [['Can I create an account now?', 'Yes. Create your account, configure your operation and continue to payment.'], ['What does annual billing mean?', 'You receive twelve months of service and are charged the equivalent of ten months under the current Home Guide structure.'], ['Can I pay in dollars or colones?', 'The estimate can be displayed in USD or CRC under the current configuration.'], ['Can I change my setup later?', 'Yes. You can enable or adjust capabilities as your operation changes, subject to current account rules.'], ['Is Home Guide only for properties?', 'No. Home Guide organizes work connected to physical sites and supports different operating configurations.'], ['Is Home Guide a plant-rental system?', 'No. Rentals are an optional capability used by some operations. They do not define the product.']] },
    final: { title: 'Keep your operation connected from the place to the result.', body: 'Organize what exists, coordinate the work, document what happened and keep the information available to the people who need it.', create: 'Create account', signIn: 'Sign in' },
    footer: 'Operations connected to where work happens.',
  },
  de: {
    nav: { how: 'So funktioniert es', visibility: 'Übersicht', capabilities: 'Funktionen', pricing: 'Preise', signIn: 'Anmelden', create: 'Konto erstellen', menu: 'Navigation öffnen' },
    hero: { eyebrow: 'VERNETZTE ABLÄUFE FÜR JEDE IMMOBILIE', title: 'Ein lebendiger Betriebsnachweis für jede Immobilie.', body: 'Home Guide verbindet Immobilien, Kunden, Bereiche, Anlagen, Aufgaben, Besuche, Pflanzen, Personal, Dokumente und Nachweise, damit Büro, Außendienst und Kunde im selben Kontext arbeiten.', support: 'Aktivieren Sie nur die Funktionen, die Ihr Betrieb benötigt.', primary: 'Konto erstellen', secondary: 'So funktioniert es', imageAlt: 'Verwaltete Immobilie mit gestalteten Außenanlagen' },
    problem: { eyebrow: 'DAS PROBLEM', title: 'Die Informationen sind vorhanden. Das Problem ist, den Betrieb jedes Mal neu zusammenzusetzen.', body: 'Der Plan kann in einem System liegen, Aufgaben in einem anderen, Fotos in einem Chat und die Historie bei verschiedenen Personen. Alles ist vorhanden, aber nicht immer mit Ort, Anlage, Verantwortung und ausgeführter Arbeit verbunden.', rows: [['Getrennter Kontext', 'Immobilien, Bereiche, Anlagen, Aufgaben, Dokumente und Fotos können ohne gemeinsame Betriebsstruktur bestehen.'], ['Arbeit ohne Kontinuität', 'Eine erledigte Aufgabe hält nicht immer klar fest, wo sie stattfand, wer sie ausführte, welche Anlage betroffen war und welcher Nachweis entstand.'], ['Neuaufbau bei jeder Anfrage', 'Wenn Kunde, Manager oder Eigentümer eine Antwort benötigt, sammelt das Team bereits erzeugte Informationen erneut.']] },
    how: { eyebrow: 'SO FUNKTIONIERT ES', title: 'Der Datensatz begleitet die Arbeit.', body: 'Home Guide bewahrt den Kontext von der Organisation eines Standorts bis zur Übergabe des Ergebnisses an den Kunden.', steps: [['ORGANISIEREN', 'Kunden, Immobilien, Bereiche und Anlagen bilden eine klare Struktur. Karten, Dokumente und QR-Etiketten verbinden jeden Eintrag mit einem realen Ort.'], ['AUSFÜHREN', 'Planen Sie Aufgaben, Besuche, Pflegeroutinen und Schichten. Jede Person sieht die für ihre Rolle relevanten Arbeiten und Werkzeuge.'], ['DOKUMENTIEREN', 'Fotos, Zeit, Ort und Protokolle machen erledigte Arbeit zu einem überprüfbaren Betriebsnachweis.'], ['TEILEN', 'Portale, Handbücher, Berichte, Erinnerungen und Dokumente machen Felddaten für Kunden nutzbar.']] },
    connected: { eyebrow: 'VERNETZTE DATEN', title: 'Ein Datensatz, viele Nutzungen.', body: 'Während der Arbeit erfasste Daten bleiben für andere Prozesse verfügbar. Der Kontext muss nicht jedes Mal neu aufgebaut werden.', routes: [['Immobilie', ['Bereiche', 'Anlagen', 'Aufgaben', 'Dokumente']], ['Aufgabe / Besuch', ['Verantwortliche Person', 'Zeit', 'Ort', 'Nachweis']], ['Pflanze / Standort', ['Protokoll', 'Pflege', 'Historie', 'Ersatz']], ['Erledigte Arbeit', ['Eintrag', 'Bericht', 'Kundenportal', 'Nachverfolgung']]] },
    audience: { eyebrow: 'FÜR WEN', title: 'Eine Betriebsgrundlage für Teams mit Verantwortung für reale Orte.', body: 'Die Struktur passt sich dem Betrieb an und bewahrt den gemeinsamen Kontext zwischen Büro, Außendienst und Kunde.', groups: [['Immobilien- und Anwesenverwaltung', 'Koordinieren Sie mehrere Immobilien, Verantwortliche, Dokumente und Arbeiten in einem konsistenten Nachweis.'], ['Landschafts- und Gartenbetrieb', 'Verbinden Sie Aufgaben, Bereiche, Anlagen und Nachweise mit dem genauen Arbeitsort.'], ['Pflanzenvermietung und -pflege', 'Verbinden Sie Standorte, Protokolle, Besuche, Pflege, Vorfälle und Ersatz.'], ['Gebäude- und Instandhaltungsbetrieb', 'Organisieren Sie wiederkehrende Pflichten, Geräte, Schichten und Ergebnisse je Standort.']] },
    visibility: { eyebrow: 'BETRIEBSÜBERSICHT', title: 'Sehen Sie den vollständigen Kontext, nicht nur eine einzelne Aufgabe.', body: 'Jeder Eintrag kann Ort, Verantwortung, Status und Nachweis zusammenführen und den nächsten Schritt erklären.', labels: ['Immobilie', 'Bereich', 'Zugewiesene Arbeit', 'Verantwortlich', 'Status', 'Letzter Nachweis', 'Nächster Schritt', 'Für Kunden sichtbar'], values: ['Immobilieneintrag', 'Nordgarten', 'Bewässerung prüfen', 'Außendienstteam', 'In Prüfung', 'Foto und Protokoll', 'Nachverfolgung bestätigen', 'Nach Freigabe'], demo: 'Darstellung eines Betriebsnachweises' },
    capabilities: { eyebrow: 'FUNKTIONEN', title: 'Werkzeuge, die der Struktur Ihres Betriebs folgen.', body: 'Aktivieren Sie benötigte Funktionen und halten Sie alles im selben Betriebsnachweis.', items: [['Kartierte Standorte', 'Satellitenkarten, gezeichnete Bereiche, verortete Anlagen und KML/KMZ-Import.'], ['Aufgaben und Besuche', 'Räumliche Arbeit, Kalender, Pflegeroutinen, Check-ins und geführte Besuche.'], ['Felddokumentation', 'Fotos, QR, Zeit, Ort und Protokolle im Zusammenhang mit der Arbeit.'], ['Pflanzenpflege', 'Profile, Protokolle, Standorte, Bewässerung, Vorfälle und Ersatz.'], ['Personal und Werkzeuge', 'Schichten, Zuweisungen, Bestand, Ausgabe und bestätigte Rückgabe.'], ['Kundenübergabe', 'Private Portale, PDF-Handbücher, Berichte, Erinnerungen, Dokumente und Rechnungen.']] },
    differences: { eyebrow: 'STRUKTURELLE UNTERSCHIEDE', title: 'Der Wert liegt darin, die Beziehung zwischen allen Teilen zu bewahren.', body: 'Home Guide trennt die Ausführung nicht von ihrem betrieblichen Kontext.', items: [['RÄUMLICHER KONTEXT', 'Arbeit bleibt mit der Immobilie, dem Bereich oder der Anlage verbunden, wo sie stattfand.'], ['BETRIEBLICHE KONTINUITÄT', 'Der Datensatz begleitet den Prozess von Planung über Abschluss bis Prüfung.'], ['FELDNACHWEIS', 'Foto, Zeit, Ort und zugehörige Einträge bleiben mit der Arbeit verbunden.'], ['ROLLENBASIERTE MODULARITÄT', 'Teams arbeiten im selben Kontext, ohne irrelevante Werkzeuge zu sehen.'], ['KUNDENÜBERGABE', 'Einträge werden zu Berichten, Handbüchern und kontrollierten Ansichten, ohne sie neu aufzubauen.']] },
    trust: { eyebrow: 'VERTRAUEN', title: 'Klarer Zugriff. Private Einträge. Nachvollziehbare Historie.', body: 'Betriebsinformationen behalten Zugriffskontrollen und eine nützliche Historie zur Prüfung der Arbeit.', items: [['Rollenbasierter Zugriff', 'Eigentümer, Manager und Teams sehen die passenden Werkzeuge und Einträge.'], ['Private Dokumente und Fotos', 'Geschützte Dateien werden über zeitlich begrenzte Zugriffe bereitgestellt.'], ['Nachvollziehbare Historie', 'Check-ins, Abschlüsse und Pflegeeinträge halten fest, wer was wann getan hat.']] },
    pricing: { eyebrow: 'PREISE', title: 'Konfigurieren Sie das Konto, das Ihr Betrieb benötigt.', body: 'Beginnen Sie mit der Anzahl der Immobilien und aktivieren Sie Spezialmodule nach Bedarf.', monthly: 'Monatlich', annual: 'Jährlich', annualNote: '10 Monate zahlen, 12 nutzen', properties: 'Immobilien', perProperty: 'pro Immobilie / Monat', extras: 'Optionale Module', accountMonth: 'Konto / Monat', summary: 'Ihre Schätzung', dueMonthly: 'pro Monat', dueAnnual: 'jährlich berechnet', saving: 'Ersparnis', continue: 'Konto erstellen und fortfahren', included: 'In jedem Konto enthalten', includedItems: ['Kunden, Immobilien und Anlagen', 'Aufgaben, Nachweise und Berichte', 'Oberfläche EN, ES und DE', 'Anzeige in USD und CRC'], decrease: 'Immobilien reduzieren', increase: 'Immobilien erhöhen' },
    faq: { eyebrow: 'HÄUFIGE FRAGEN', title: 'Vor dem Start', items: [['Kann ich jetzt ein Konto erstellen?', 'Ja. Erstellen Sie Ihr Konto, wählen Sie die Konfiguration und schließen Sie die Zahlung mit ONVO ab.'], ['Was bedeutet jährliche Abrechnung?', 'Sie erhalten 12 Monate Service und bezahlen den Gegenwert von 10 Monaten.'], ['Kann ich in CRC bezahlen?', 'Ja. Der Checkout unterstützt USD und CRC; die Schätzung ist in beiden Währungen sichtbar.'], ['Kann ich meine Konfiguration später ändern?', 'Ja. Sie können Immobilien und optionale Module ergänzen, wenn sich Ihr Betrieb verändert.']] },
    final: { title: 'Geben Sie jeder Immobilie einen Betriebsnachweis, der nach Abschluss der Arbeit fortbesteht.', body: 'Organisieren Sie den Betrieb, bewahren Sie den Kontext und teilen Sie Ergebnisse im selben System.', create: 'Konto erstellen', signIn: 'Anmelden' },
    footer: 'Vernetzte Abläufe für Immobilien-, Landschafts-, Pflanzen- und Facility-Teams.',
  },
};
