export type LandingLanguage = 'en' | 'es' | 'de';

type LocalCopy = {
  seo: { title: string; description: string };
  nav: { how: string; audience: string; capabilities: string; pricing: string; signIn: string; create: string; menu: string };
  hero: { eyebrow: string; title: string; body: string; support: string; primary: string; secondary: string; imageAlt: string };
  problem: { eyebrow: string; title: string; body: string; rows: [string, string][] };
  how: { eyebrow: string; title: string; body: string; steps: [string, string][] };
  connected: { eyebrow: string; title: string; body: string; modelLabel: string; modelNote: string; model: string[]; routes: [string, string[]][] };
  audience: { eyebrow: string; title: string; body: string; groups: [string, string][] };
  visibility: { eyebrow: string; title: string; body: string; labels: string[]; values: string[]; demo: string };
  capabilities: { eyebrow: string; title: string; body: string; items: [string, string][] };
  differences: { eyebrow: string; title: string; body: string; items: [string, string][] };
  trust: { eyebrow: string; title: string; body: string; items: [string, string][] };
  pricing: Record<string, string | string[]>;
  faq: { eyebrow: string; title: string; items: [string, string][] };
  final: { title: string; body: string; create: string; signIn: string };
  footer: string;
};

export const landingCopy: Record<LandingLanguage, LocalCopy> = {
  es: {
    seo: { title: 'Home Guide | Operaciones conectadas al lugar donde ocurren', description: 'Home Guide conecta sitios, activos, trabajo, personas, documentos e información operativa para conservar el contexto desde la planificación hasta el resultado.' },
    nav: { how: 'Cómo funciona', audience: 'Para quién es', capabilities: 'Capacidades', pricing: 'Precios', signIn: 'Ingresar', create: 'Crear cuenta', menu: 'Abrir navegación' },
    hero: { eyebrow: 'OPERACIONES CONECTADAS AL LUGAR DONDE OCURREN', title: 'Cada lugar tiene una operación. Home Guide la mantiene conectada.', body: 'Organice sitios, activos, trabajo, personas, documentos y registros en un mismo contexto. Desde lo que existe en un lugar hasta lo que se hizo, quién lo hizo y qué debe ocurrir después.', support: 'Configure Home Guide según su operación. Active únicamente las capacidades que necesita.', primary: 'Crear cuenta', secondary: 'Ver cómo funciona', imageAlt: 'Propiedad y entorno físico donde se coordinan operaciones de campo' },
    problem: { eyebrow: 'EL PROBLEMA', title: 'El trabajo ocurre en lugares reales. La información suele quedar separada de ellos.', body: 'Una fotografía, una tarea, un activo o un documento pueden existir y aun así perder gran parte de su valor operativo cuando no queda claro a qué lugar, trabajo, persona o cliente pertenecen.', rows: [['INFORMACIÓN SIN CONTEXTO', 'Una fotografía, tarea, activo o documento pierde valor operativo cuando no queda claro a qué lugar, cliente o trabajo pertenece.'], ['TRABAJO DIFÍCIL DE RECONSTRUIR', 'Saber qué se hizo, dónde ocurrió, quién lo hizo y qué falta todavía puede exigir consultar distintos registros y personas.'], ['DISTINTAS VERSIONES DE LA MISMA OPERACIÓN', 'Oficina, campo, administración y cliente pueden terminar trabajando con fragmentos distintos de la misma historia.']] },
    how: { eyebrow: 'CÓMO FUNCIONA', title: 'El registro acompaña al trabajo.', body: 'Home Guide conserva el contexto desde que se organiza un sitio hasta que el resultado llega a quien necesita verlo.', steps: [['ESTRUCTURAR', 'Clientes, propiedades o sitios, zonas y activos crean el contexto donde ocurre la operación.'], ['OPERAR', 'Tareas, visitas, mantenimiento, cuidados, turnos y otros flujos ocurren dentro de ese contexto.'], ['REGISTRAR', 'Personas, tiempo, fotografías, documentos, ubicación y cambios dejan una historia operativa.'], ['COMPARTIR', 'Los mismos registros pueden alimentar reportes, manuales, facturación, portales y seguimiento según la configuración.']] },
    connected: { eyebrow: 'DATOS CONECTADOS', title: 'Un registro, múltiples usos.', body: 'La información capturada durante el trabajo queda disponible para los demás procesos que la necesitan. El contexto no tiene que reconstruirse cada vez.', modelLabel: 'Modelo operativo conectado', modelNote: 'Cada relación se utiliza cuando aplica. Una operación puede comenzar en un sitio y sus registros pueden vincularse al nivel correspondiente.', model: ['Cliente / propietario', 'Sitio / propiedad', 'Zona', 'Activo', 'Trabajo', 'Persona', 'Evidencia'], routes: [['Propiedad / sitio', ['Zonas', 'Activos', 'Tareas', 'Documentos']], ['Tarea / visita', ['Responsable', 'Hora', 'Ubicación', 'Evidencia']], ['Activo', ['Condición', 'Mantenimiento', 'Documentos', 'Historial']], ['Trabajo completado', ['Registro', 'Reporte', 'Portal del cliente', 'Seguimiento']]] },
    audience: { eyebrow: 'CONFIGURACIONES OPERATIVAS', title: 'Un mismo sistema. Distintas operaciones.', body: 'Estos son ejemplos de configuración sobre un mismo modelo operativo, no industrias exclusivas.', groups: [['Servicios y mantenimiento de propiedades', 'Coordine sitios, activos, tareas, mantenimiento, documentación y trabajo recurrente.'], ['Operaciones de campo', 'Coordine asignaciones, visitas, herramientas, horas, personal y comprobación del trabajo.'], ['Servicio de activos y equipos', 'Registre equipos, ubicación, condición, mantenimiento e historial.'], ['Paisajismo y áreas verdes', 'Organice propiedades, zonas, visitas, tareas, equipos y registros de campo.'], ['Administración de propiedades', 'Mantenga propiedades, tareas, documentos, recordatorios y servicios bajo un mismo contexto.'], ['Servicios de plantas e interiorismo vegetal', 'Gestione ubicaciones, plantas, cuidados, visitas, reemplazos y, cuando corresponda, alquileres.'], ['Operación propia', 'Administre sus propiedades, activos, documentos y mantenimiento sin depender de un modelo de clientes.'], ['Configuración personalizada', 'Active los módulos que correspondan cuando su flujo no coincida con una configuración predefinida.']] },
    visibility: { eyebrow: 'VISIBILIDAD OPERATIVA', title: 'El contexto permanece visible.', body: 'En lugar de ver registros aislados, Home Guide permite entender cómo se relacionan el sitio, el activo, el trabajo, la persona responsable y la información disponible.', labels: ['Cliente / propietario', 'Sitio', 'Zona', 'Activo', 'Trabajo', 'Responsable', 'Estado', 'Última evidencia', 'Próxima acción', 'Visibilidad del cliente', 'Documentos relacionados'], values: ['Registro general', 'Sitio operativo', 'Zona de servicio', 'Activo registrado', 'Inspección programada', 'Equipo asignado', 'En revisión', 'Fotografía y check-in', 'Confirmar seguimiento', 'Pendiente de compartir', 'Manual y orden de trabajo'], demo: 'Representación del modelo operativo' },
    capabilities: { eyebrow: 'CAPACIDADES', title: 'Active las capacidades que corresponden a su operación.', body: 'Las herramientas comparten el mismo contexto, pero cada organización decide qué necesita.', items: [['LUGARES Y CONTEXTO', 'Clientes o propietarios, sitios, mapas, zonas, activos, GPS e importación KML/KMZ.'], ['TRABAJO', 'Tareas, visitas, mantenimiento, rutinas de cuidado y recordatorios.'], ['PERSONAS Y RECURSOS', 'Equipos, turnos, horas, tarifas, herramientas e inventario.'], ['REGISTROS Y EVIDENCIA', 'Fotografías, documentos, check-ins, ubicación, historial, reportes y manuales.'], ['ENTREGA AL CLIENTE', 'Portales, reportes, recordatorios, documentos y registros de facturación y pagos.'], ['OPERACIONES ESPECIALIZADAS', 'Plantas, macetas, protocolos de cuidado, alquileres y otros flujos configurables.']] },
    differences: { eyebrow: 'DIFERENCIAS ESTRUCTURALES', title: 'La diferencia está en cómo se conserva el contexto.', body: 'Home Guide conecta las piezas de la operación sin obligar a todos los equipos a trabajar de la misma manera.', items: [['CONTEXTO ESPACIAL', 'El trabajo permanece relacionado con el sitio, zona o activo donde ocurre, cuando ese nivel aplica.'], ['CONTINUIDAD OPERATIVA', 'El registro acompaña al proceso desde la planificación hasta la ejecución y revisión.'], ['EVIDENCIA LIGADA AL TRABAJO', 'Fotografías, tiempo, ubicación y documentos pueden permanecer asociados a la actividad que los produjo.'], ['MODULARIDAD POR OPERACIÓN', 'Cada organización activa las capacidades que necesita sin obligar a todas las operaciones a funcionar igual.'], ['UNA MISMA BASE PARA DISTINTAS VISTAS', 'El mismo contexto puede servir a campo, administración y cliente sin reconstruirse como sistemas separados.'], ['ADAPTACIÓN AL MODELO OPERATIVO', 'Servicios de plantas, paisajismo, propiedades, activos y otras configuraciones extienden el mismo modelo sin convertirse en productos separados.']] },
    trust: { eyebrow: 'CONTROL Y TRAZABILIDAD', title: 'Acceso claro. Registros privados. Historial trazable.', body: 'La información operativa conserva controles de acceso y una historia útil para revisar el trabajo.', items: [['Acceso por rol', 'Dueños, administradores, equipos y otros perfiles ven las herramientas y registros que corresponden a su trabajo.'], ['Registros privados', 'Documentos y fotografías utilizan acceso protegido de acuerdo con la arquitectura actual.'], ['Historial operativo', 'Trabajo, visitas, cuidados, check-ins y otros eventos conservan quién hizo qué y cuándo cuando el flujo correspondiente lo registra.']] },
    pricing: { eyebrow: 'PRECIOS', title: 'Configure la cuenta que su operación necesita.', body: 'Comience con la cantidad de propiedades y active capacidades especializadas cuando las necesite.', monthly: 'Mensual', annual: 'Anual', annualNote: 'Pague 10 meses, use 12', properties: 'Propiedades', perProperty: 'por propiedad / mes', extras: 'Módulos y capacidades opcionales', extrasBody: 'Nueve capacidades opcionales con precio por cuenta. Active solo las que su operación necesita.', groupOperation: 'Operación', groupOperationBody: 'Ejecución diaria del trabajo en sitio y del equipo.', groupManagement: 'Gestión', groupManagementBody: 'Recursos, comunicación con clientes, documentación y cobros.', groupAnalysis: 'Análisis', groupAnalysisBody: 'Lectura espacial avanzada del terreno.', groupSpecialized: 'Especializado', groupSpecializedBody: 'Capacidades para operaciones con plantas. La venta, el alquiler o la rotación dependen de su configuración, no de un cobro aparte.', accountMonth: 'cuenta / mes', summary: 'Su estimado', dueMonthly: 'por mes', dueAnnual: 'facturado anualmente', saving: 'Ahorro', continue: 'Crear cuenta y continuar', included: 'Base de cada cuenta', includedItems: ['Clientes, propiedades y activos', 'Tareas, registros e informes', 'Interfaz EN, ES y DE', 'Visualización USD y CRC'], decrease: 'Reducir propiedades', increase: 'Aumentar propiedades', catalogTitle: 'Mapa completo de capacidades', catalogBody: 'Home Guide reúne un conjunto de módulos funcionales que se activan según la configuración de cada operación.', catalogNote: 'La disponibilidad depende de la configuración elegida y de las capacidades activadas.', capabilityCore: 'Estructura y registros', capabilityField: 'Trabajo de campo', capabilityCare: 'Cuidado y ciclos de servicio', capabilityAdmin: 'Documentación y administración' },
    faq: { eyebrow: 'PREGUNTAS FRECUENTES', title: 'Antes de comenzar', items: [['¿Puedo crear una cuenta ahora?', 'Sí. Cree su cuenta, configure su operación y continúe al proceso de pago.'], ['¿Qué significa la modalidad anual?', 'Recibe doce meses de servicio y se cobra el equivalente a diez meses según la estructura actual de Home Guide.'], ['¿Puedo pagar en dólares o colones?', 'El estimado admite visualización en USD y CRC según la configuración actual.'], ['¿Puedo cambiar mi configuración después?', 'Sí. Puede activar o ajustar capacidades a medida que cambia su operación, sujeto a las reglas actuales de la cuenta.'], ['¿Home Guide es solo para propiedades?', 'No. Home Guide organiza trabajo ligado a sitios físicos y admite distintas configuraciones operativas.'], ['¿Mi equipo puede usarlo desde el teléfono en campo?', 'Sí. Las tareas, fotografías, ubicación y registros de trabajo están diseñados para usarse en sitio, desde el móvil.']] },
    final: { title: 'Conserve el contexto de su operación desde el lugar hasta el resultado.', body: 'Organice lo que existe, coordine el trabajo, documente lo ocurrido y mantenga la información disponible para quien la necesita.', create: 'Crear cuenta', signIn: 'Ingresar' },
    footer: 'Operaciones conectadas al lugar donde ocurre el trabajo.',
  },
  en: {
    seo: { title: 'Home Guide | Operations connected to the places where work happens', description: 'Home Guide connects sites, assets, work, people, documents and operational records so physical operations keep their context from planning through completion.' },
    nav: { how: 'How it works', audience: "Who it's for", capabilities: 'Capabilities', pricing: 'Pricing', signIn: 'Sign in', create: 'Create account', menu: 'Open navigation' },
    hero: { eyebrow: 'OPERATIONS CONNECTED TO WHERE WORK HAPPENS', title: 'Every place has an operation. Home Guide keeps it connected.', body: 'Organize sites, assets, work, people, documents and records within the same operational context. From what exists in a place to what was done, who did it and what needs to happen next.', support: 'Configure Home Guide around your operation. Enable only the capabilities you need.', primary: 'Create account', secondary: 'See how it works', imageAlt: 'A physical property and environment where field operations take place' },
    problem: { eyebrow: 'THE PROBLEM', title: 'Work happens in physical places. The information often becomes separated from them.', body: 'A photo, task, asset or document can exist and still lose much of its operational value when it is unclear which place, work, person or client it belongs to.', rows: [['INFORMATION WITHOUT CONTEXT', 'A photo, task, asset or document loses operational value when it is unclear which place, client or piece of work it belongs to.'], ['WORK THAT MUST BE RECONSTRUCTED', 'Understanding what happened, where, who did it and what remains open may require checking multiple records and people.'], ['DIFFERENT VERSIONS OF THE SAME OPERATION', 'Office, field teams, management and clients can end up working from different fragments of the same story.']] },
    how: { eyebrow: 'HOW IT WORKS', title: 'The record follows the work.', body: 'Home Guide preserves context from the moment a site is organized until the result reaches the person who needs it.', steps: [['STRUCTURE', 'Clients, properties or sites, zones and assets create the context in which the operation happens.'], ['OPERATE', 'Tasks, visits, maintenance, care routines, shifts and other workflows happen inside that context.'], ['RECORD', 'People, time, photos, documents, location and changes build an operational history.'], ['SHARE', 'The same records can support reports, manuals, billing, portals and follow-up depending on the configuration.']] },
    connected: { eyebrow: 'CONNECTED DATA', title: 'One record, multiple uses.', body: 'Information captured during work remains available to the other processes that need it. Context does not have to be rebuilt every time.', modelLabel: 'Connected operating model', modelNote: 'Each relationship is used when it applies. An operation can begin at a site, and records can connect at the relevant level.', model: ['Client / owner', 'Site / property', 'Zone', 'Asset', 'Work', 'Person', 'Evidence'], routes: [['Property / site', ['Zones', 'Assets', 'Tasks', 'Documents']], ['Task / visit', ['Responsible person', 'Time', 'Location', 'Evidence']], ['Asset', ['Condition', 'Maintenance', 'Documents', 'History']], ['Completed work', ['Record', 'Report', 'Client portal', 'Follow-up']]] },
    audience: { eyebrow: 'OPERATING CONFIGURATIONS', title: 'One system. Different operations.', body: 'These are examples of configurations built on the same operating model, not exclusive industries.', groups: [['Property services and maintenance', 'Coordinate sites, assets, tasks, maintenance, documentation and recurring work.'], ['Field operations', 'Coordinate assignments, visits, tools, hours, people and proof of completed work.'], ['Asset and equipment service', 'Record equipment, location, condition, maintenance and history.'], ['Landscaping and grounds', 'Organize properties, zones, visits, tasks, teams and field records.'], ['Property management', 'Keep properties, tasks, documents, reminders and services in one context.'], ['Plant and interior landscape services', 'Manage placements, plants, care, visits, replacements and rentals when relevant.'], ['Own operation', 'Manage your own properties, assets, documents and maintenance without a client model.'], ['Custom configuration', 'Enable the modules that fit when your workflow does not match a predefined configuration.']] },
    visibility: { eyebrow: 'OPERATIONAL VISIBILITY', title: 'Context remains visible.', body: 'Instead of isolated records, Home Guide shows how the site, asset, work, responsible person and available information relate.', labels: ['Client / owner', 'Site', 'Zone', 'Asset', 'Work', 'Responsible person', 'Status', 'Latest evidence', 'Next action', 'Client visibility', 'Related documents'], values: ['General record', 'Operating site', 'Service zone', 'Registered asset', 'Scheduled inspection', 'Assigned team', 'Under review', 'Photo and check-in', 'Confirm follow-up', 'Pending share', 'Manual and work order'], demo: 'Operating model representation' },
    capabilities: { eyebrow: 'CAPABILITIES', title: 'Enable the capabilities that fit your operation.', body: 'The tools share the same context, while each organization decides what it needs.', items: [['PLACES AND CONTEXT', 'Clients or owners, sites, maps, zones, assets, GPS and KML/KMZ import.'], ['WORK', 'Tasks, visits, maintenance, care routines and reminders.'], ['PEOPLE AND RESOURCES', 'Teams, shifts, hours, rates, tools and inventory.'], ['RECORDS AND EVIDENCE', 'Photos, documents, check-ins, location, history, reports and manuals.'], ['CLIENT DELIVERY', 'Portals, reports, reminders, documents, billing and payment records.'], ['SPECIALIZED OPERATIONS', 'Plants, pots, care protocols, rentals and other configurable workflows.']] },
    differences: { eyebrow: 'STRUCTURAL DIFFERENCES', title: 'The difference is how context is preserved.', body: 'Home Guide connects operational pieces without forcing every team to work in the same way.', items: [['SPATIAL CONTEXT', 'Work remains related to the site, zone or asset where it happens when that level applies.'], ['OPERATIONAL CONTINUITY', 'The record follows the process from planning through execution and review.'], ['EVIDENCE CONNECTED TO WORK', 'Photos, time, location and documents can remain associated with the activity that produced them.'], ['MODULARITY BY OPERATION', 'Each organization enables the capabilities it needs without forcing every operation into the same model.'], ['ONE FOUNDATION FOR DIFFERENT VIEWS', 'The same context can serve field teams, management and clients without becoming separate systems.'], ['ADAPTS TO THE OPERATING MODEL', 'Plant services, landscaping, property services, asset operations and other configurations extend the same model instead of becoming separate products.']] },
    trust: { eyebrow: 'CONTROL AND TRACEABILITY', title: 'Clear access. Private records. Traceable history.', body: 'Operational information retains access controls and a useful history for reviewing work.', items: [['Role-based access', 'Owners, managers, teams and other profiles see the tools and records relevant to their work.'], ['Private records', 'Documents and photographs use protected access within the current architecture.'], ['Operational history', 'Work, visits, care, check-ins and other events preserve who did what and when when the corresponding workflow records it.']] },
    pricing: { eyebrow: 'PRICING', title: 'Configure the account your operation needs.', body: 'Start with the number of properties and activate specialist capabilities when you need them.', monthly: 'Monthly', annual: 'Annual', annualNote: 'Pay for 10 months, use 12', properties: 'Properties', perProperty: 'per property / month', extras: 'Optional modules and capabilities', extrasBody: 'Nine optional capabilities, priced per account. Turn on only what your operation needs.', groupOperation: 'Operation', groupOperationBody: 'Daily execution of on-site work and the team behind it.', groupManagement: 'Management', groupManagementBody: 'Resources, client communication, documentation and billing.', groupAnalysis: 'Analysis', groupAnalysisBody: 'Advanced spatial reading of the terrain.', groupSpecialized: 'Specialized', groupSpecializedBody: 'Capabilities for plant operations. Selling, renting or rotating depends on your configuration, not on a separate charge.', accountMonth: 'account / month', summary: 'Your estimate', dueMonthly: 'per month', dueAnnual: 'billed annually', saving: 'Saving', continue: 'Create account and continue', included: 'Every account starts with', includedItems: ['Clients, properties and assets', 'Tasks, records and reports', 'EN, ES and DE interface', 'USD and CRC display'], decrease: 'Decrease properties', increase: 'Increase properties', catalogTitle: 'Complete capability map', catalogBody: 'Home Guide brings together a set of functional modules, enabled according to each operation’s configuration.', catalogNote: 'Availability depends on the selected configuration and the capabilities you enable.', capabilityCore: 'Structure and records', capabilityField: 'Field work', capabilityCare: 'Care and service cycles', capabilityAdmin: 'Documentation and administration' },
    faq: { eyebrow: 'FREQUENT QUESTIONS', title: 'Before you begin', items: [['Can I create an account now?', 'Yes. Create your account, configure your operation and continue to payment.'], ['What does annual billing mean?', 'You receive twelve months of service and are charged the equivalent of ten months under the current Home Guide structure.'], ['Can I pay in dollars or colones?', 'The estimate can be displayed in USD or CRC under the current configuration.'], ['Can I change my setup later?', 'Yes. You can enable or adjust capabilities as your operation changes, subject to current account rules.'], ['Is Home Guide only for properties?', 'No. Home Guide organizes work connected to physical sites and supports different operating configurations.'], ['Can my team use it from a phone in the field?', 'Yes. Tasks, photos, location and work records are designed for on-site use from mobile.']] },
    final: { title: 'Keep your operation connected from the place to the result.', body: 'Organize what exists, coordinate the work, document what happened and keep the information available to the people who need it.', create: 'Create account', signIn: 'Sign in' },
    footer: 'Operations connected to where work happens.',
  },
  de: {
    seo: { title: 'Home Guide | Abläufe verbunden mit den Orten, an denen Arbeit stattfindet', description: 'Home Guide verbindet Standorte, Anlagen, Arbeit, Personen, Dokumente und Betriebsinformationen, damit der Kontext von der Planung bis zum Ergebnis erhalten bleibt.' },
    nav: { how: 'So funktioniert es', audience: 'Für wen', capabilities: 'Funktionen', pricing: 'Preise', signIn: 'Anmelden', create: 'Konto erstellen', menu: 'Navigation öffnen' },
    hero: { eyebrow: 'ABLÄUFE VERBUNDEN MIT DEM ORT, AN DEM ARBEIT STATTFINDET', title: 'Jeder Ort hat einen Betrieb. Home Guide hält ihn verbunden.', body: 'Organisieren Sie Standorte, Anlagen, Arbeit, Personen, Dokumente und Einträge in einem gemeinsamen betrieblichen Kontext. Von dem, was an einem Ort vorhanden ist, bis zu dem, was erledigt wurde, wer es erledigt hat und was als Nächstes ansteht.', support: 'Konfigurieren Sie Home Guide passend zu Ihrem Betrieb. Aktivieren Sie nur die Funktionen, die Sie benötigen.', primary: 'Konto erstellen', secondary: 'So funktioniert es', imageAlt: 'Ein physischer Standort, an dem Außendienstarbeit koordiniert wird' },
    problem: { eyebrow: 'DAS PROBLEM', title: 'Arbeit findet an realen Orten statt. Die Informationen werden oft davon getrennt.', body: 'Ein Foto, eine Aufgabe, eine Anlage oder ein Dokument kann vorhanden sein und dennoch an betrieblichem Wert verlieren, wenn der Bezug zu Ort, Arbeit, Person oder Kunde unklar ist.', rows: [['INFORMATIONEN OHNE KONTEXT', 'Ein Eintrag verliert an Wert, wenn die Zuordnung zu Ort, Kunde oder Arbeit unklar ist.'], ['ARBEIT MUSS REKONSTRUIERT WERDEN', 'Was geschah, wo es geschah, wer es ausführte und was offen bleibt, muss häufig aus mehreren Quellen zusammengesetzt werden.'], ['VERSCHIEDENE VERSIONEN DESSELBEN BETRIEBS', 'Büro, Außendienst, Verwaltung und Kunden können mit unterschiedlichen Fragmenten derselben Geschichte arbeiten.']] },
    how: { eyebrow: 'SO FUNKTIONIERT ES', title: 'Der Eintrag begleitet die Arbeit.', body: 'Home Guide bewahrt den Kontext von der Organisation eines Standorts bis das Ergebnis die richtige Person erreicht.', steps: [['STRUKTURIEREN', 'Kunden, Immobilien oder Standorte, Zonen und Anlagen schaffen den Kontext des Betriebs.'], ['BETREIBEN', 'Aufgaben, Besuche, Wartung, Pflegeroutinen, Schichten und weitere Abläufe finden in diesem Kontext statt.'], ['DOKUMENTIEREN', 'Personen, Zeit, Fotos, Dokumente, Ort und Änderungen bilden eine Betriebshistorie.'], ['TEILEN', 'Dieselben Einträge können je nach Konfiguration Berichte, Handbücher, Abrechnung, Portale und Nachverfolgung unterstützen.']] },
    connected: { eyebrow: 'VERNETZTE DATEN', title: 'Ein Eintrag, viele Nutzungen.', body: 'Während der Arbeit erfasste Informationen bleiben für andere Prozesse verfügbar. Der Kontext muss nicht jedes Mal neu aufgebaut werden.', modelLabel: 'Vernetztes Betriebsmodell', modelNote: 'Jede Beziehung wird genutzt, wenn sie zutrifft. Ein Betrieb kann direkt an einem Standort beginnen; Einträge werden mit der passenden Ebene verbunden.', model: ['Kunde / Eigentümer', 'Standort / Immobilie', 'Zone', 'Anlage', 'Arbeit', 'Person', 'Nachweis'], routes: [['Immobilie / Standort', ['Zonen', 'Anlagen', 'Aufgaben', 'Dokumente']], ['Aufgabe / Besuch', ['Verantwortliche Person', 'Zeit', 'Ort', 'Nachweis']], ['Anlage', ['Zustand', 'Wartung', 'Dokumente', 'Historie']], ['Erledigte Arbeit', ['Eintrag', 'Bericht', 'Kundenportal', 'Nachverfolgung']]] },
    audience: { eyebrow: 'BETRIEBSKONFIGURATIONEN', title: 'Ein System. Unterschiedliche Betriebe.', body: 'Dies sind Konfigurationsbeispiele auf demselben Betriebsmodell, keine exklusiven Branchen.', groups: [['Immobilienservice und Instandhaltung', 'Koordinieren Sie Standorte, Anlagen, Aufgaben, Wartung, Dokumentation und wiederkehrende Arbeit.'], ['Außendienst', 'Koordinieren Sie Einsätze, Besuche, Werkzeuge, Stunden, Personal und Arbeitsnachweise.'], ['Anlagen- und Geräteservice', 'Erfassen Sie Geräte, Standort, Zustand, Wartung und Historie.'], ['Landschaftsbau und Grünflächen', 'Organisieren Sie Immobilien, Zonen, Besuche, Aufgaben, Teams und Feldeinträge.'], ['Immobilienverwaltung', 'Halten Sie Immobilien, Aufgaben, Dokumente, Erinnerungen und Services in einem Kontext.'], ['Pflanzen- und Innenraumbegrünung', 'Verwalten Sie Standorte, Pflanzen, Pflege, Besuche, Ersatz und bei Bedarf Vermietung.'], ['Eigener Betrieb', 'Verwalten Sie eigene Immobilien, Anlagen, Dokumente und Wartung ohne Kundenmodell.'], ['Individuelle Konfiguration', 'Aktivieren Sie passende Module, wenn Ihr Ablauf keiner vordefinierten Konfiguration entspricht.']] },
    visibility: { eyebrow: 'BETRIEBSÜBERSICHT', title: 'Der Kontext bleibt sichtbar.', body: 'Statt isolierter Einträge zeigt Home Guide die Beziehungen zwischen Standort, Anlage, Arbeit, verantwortlicher Person und verfügbaren Informationen.', labels: ['Kunde / Eigentümer', 'Standort', 'Zone', 'Anlage', 'Arbeit', 'Verantwortlich', 'Status', 'Letzter Nachweis', 'Nächster Schritt', 'Kundensichtbarkeit', 'Zugehörige Dokumente'], values: ['Allgemeiner Eintrag', 'Betriebsstandort', 'Servicezone', 'Registrierte Anlage', 'Geplante Inspektion', 'Zugewiesenes Team', 'In Prüfung', 'Foto und Check-in', 'Nachverfolgung bestätigen', 'Freigabe ausstehend', 'Handbuch und Arbeitsauftrag'], demo: 'Darstellung des Betriebsmodells' },
    capabilities: { eyebrow: 'FUNKTIONEN', title: 'Aktivieren Sie die Funktionen, die zu Ihrem Betrieb passen.', body: 'Die Werkzeuge teilen denselben Kontext; jede Organisation entscheidet, was sie benötigt.', items: [['ORTE UND KONTEXT', 'Kunden oder Eigentümer, Standorte, Karten, Zonen, Anlagen, GPS und KML/KMZ-Import.'], ['ARBEIT', 'Aufgaben, Besuche, Wartung, Pflegeroutinen und Erinnerungen.'], ['PERSONEN UND RESSOURCEN', 'Teams, Schichten, Stunden, Tarife, Werkzeuge und Bestand.'], ['EINTRÄGE UND NACHWEISE', 'Fotos, Dokumente, Check-ins, Ort, Historie, Berichte und Handbücher.'], ['KUNDENBEREITSTELLUNG', 'Portale, Berichte, Erinnerungen, Dokumente sowie Abrechnungs- und Zahlungsdaten.'], ['SPEZIALISIERTE ABLÄUFE', 'Pflanzen, Töpfe, Pflegeprotokolle, Vermietung und weitere konfigurierbare Abläufe.']] },
    differences: { eyebrow: 'STRUKTURELLE UNTERSCHIEDE', title: 'Der Unterschied liegt darin, wie Kontext erhalten bleibt.', body: 'Home Guide verbindet betriebliche Teile, ohne jedes Team in denselben Ablauf zu zwingen.', items: [['RÄUMLICHER KONTEXT', 'Arbeit bleibt mit Standort, Zone oder Anlage verbunden, wenn diese Ebene zutrifft.'], ['BETRIEBLICHE KONTINUITÄT', 'Der Eintrag begleitet den Prozess von der Planung über die Ausführung bis zur Prüfung.'], ['NACHWEISE AN DER ARBEIT', 'Fotos, Zeit, Ort und Dokumente können mit der Aktivität verbunden bleiben, die sie erzeugt hat.'], ['MODULARITÄT NACH BETRIEB', 'Jede Organisation aktiviert benötigte Funktionen, ohne alle Betriebe gleich zu behandeln.'], ['EINE BASIS FÜR VERSCHIEDENE SICHTEN', 'Derselbe Kontext dient Außendienst, Verwaltung und Kunden, ohne getrennte Systeme aufzubauen.'], ['ANPASSUNG AN DAS BETRIEBSMODELL', 'Pflanzenservice, Landschaftsbau, Immobilienservice, Anlagenbetrieb und weitere Konfigurationen erweitern dasselbe Modell.']] },
    trust: { eyebrow: 'VERTRAUEN', title: 'Klarer Zugriff. Private Einträge. Nachvollziehbare Historie.', body: 'Betriebsinformationen behalten Zugriffskontrollen und eine nützliche Historie zur Prüfung der Arbeit.', items: [['Rollenbasierter Zugriff', 'Eigentümer, Manager und Teams sehen die passenden Werkzeuge und Einträge.'], ['Private Dokumente und Fotos', 'Geschützte Dateien werden über zeitlich begrenzte Zugriffe bereitgestellt.'], ['Nachvollziehbare Historie', 'Check-ins, Abschlüsse und Pflegeeinträge halten fest, wer was wann getan hat.']] },
    pricing: { eyebrow: 'PREISE', title: 'Konfigurieren Sie das Konto, das Ihr Betrieb benötigt.', body: 'Beginnen Sie mit der Anzahl der Immobilien und aktivieren Sie spezialisierte Funktionen nach Bedarf.', monthly: 'Monatlich', annual: 'Jährlich', annualNote: '10 Monate zahlen, 12 nutzen', properties: 'Immobilien', perProperty: 'pro Immobilie / Monat', extras: 'Optionale Module und Funktionen', extrasBody: 'Neun optionale Funktionen, Preis pro Konto. Aktivieren Sie nur das Nötige.', groupOperation: 'Betrieb', groupOperationBody: 'Tägliche Ausführung der Arbeit vor Ort und im Team.', groupManagement: 'Verwaltung', groupManagementBody: 'Ressourcen, Kundenkommunikation, Dokumentation und Abrechnung.', groupAnalysis: 'Analyse', groupAnalysisBody: 'Erweiterte räumliche Auswertung des Geländes.', groupSpecialized: 'Spezialisiert', groupSpecializedBody: 'Funktionen für Pflanzenbetriebe. Verkauf, Vermietung oder Rotation ergeben sich aus Ihrer Konfiguration, nicht aus einer separaten Gebühr.', accountMonth: 'Konto / Monat', summary: 'Ihre Schätzung', dueMonthly: 'pro Monat', dueAnnual: 'jährlich berechnet', saving: 'Ersparnis', continue: 'Konto erstellen und fortfahren', included: 'Grundlage jedes Kontos', includedItems: ['Kunden, Immobilien und Anlagen', 'Aufgaben, Protokolle und Berichte', 'Oberfläche EN, ES und DE', 'Anzeige in USD und CRC'], decrease: 'Immobilien reduzieren', increase: 'Immobilien erhöhen', catalogTitle: 'Vollständige Funktionsübersicht', catalogBody: 'Home Guide vereint eine Reihe von Funktionsmodulen, die je nach Betriebskonfiguration aktiviert werden.', catalogNote: 'Die Verfügbarkeit hängt von der gewählten Konfiguration und den aktivierten Funktionen ab.', capabilityCore: 'Struktur und Unterlagen', capabilityField: 'Außendienst', capabilityCare: 'Pflege und Servicezyklen', capabilityAdmin: 'Dokumentation und Verwaltung' },
    faq: { eyebrow: 'HÄUFIGE FRAGEN', title: 'Vor dem Start', items: [['Kann ich jetzt ein Konto erstellen?', 'Ja. Erstellen Sie Ihr Konto, konfigurieren Sie Ihren Betrieb und fahren Sie mit der Zahlung fort.'], ['Was bedeutet jährliche Abrechnung?', 'Sie erhalten zwölf Monate Service und bezahlen den Gegenwert von zehn Monaten.'], ['Kann ich in Dollar oder Colones bezahlen?', 'Die Schätzung kann in der aktuellen Konfiguration in USD oder CRC angezeigt werden.'], ['Kann ich meine Konfiguration später ändern?', 'Ja. Sie können Funktionen anpassen, wenn sich Ihr Betrieb verändert, vorbehaltlich der aktuellen Kontoregeln.'], ['Ist Home Guide nur für Immobilien?', 'Nein. Home Guide organisiert Arbeit an physischen Standorten und unterstützt verschiedene Betriebskonfigurationen.'], ['Kann mein Team es im Einsatz vom Handy aus nutzen?', 'Ja. Aufgaben, Fotos, Standort und Arbeitsnachweise sind für die mobile Nutzung vor Ort konzipiert.']] },
    final: { title: 'Halten Sie Ihren Betrieb vom Ort bis zum Ergebnis verbunden.', body: 'Organisieren Sie, was vorhanden ist, koordinieren Sie die Arbeit, dokumentieren Sie das Geschehen und halten Sie Informationen für die richtigen Personen verfügbar.', create: 'Konto erstellen', signIn: 'Anmelden' },
    footer: 'Abläufe verbunden mit dem Ort, an dem Arbeit stattfindet.',
  },
};
