import { useLanguage } from '@/contexts/LanguageContext';

const es = {
  sectionTitle: '¿Cómo quiere que quede?',
  sectionHint: 'Opcional. Muestre el estado actual y el resultado que espera.',
  serviceType: 'Tipo de servicio',
  current: 'Estado actual',
  reference: 'Referencia del resultado',
  referenceHint: 'Puede subir una foto para mostrar aproximadamente cómo quiere que quede.',
  agreedRef: 'Referencia acordada',
  final: 'Resultado final',
  whatChange: '¿Qué quiere cambiar?',
  whatChangePh: 'Ej.: reducir aproximadamente 30% la altura y mantener la parte inferior llena.',
  takePhoto: 'Tomar o subir foto',
  fromHistory: 'Usar foto de un servicio anterior',
  addPin: 'Toque la foto para marcar un punto',
  pinNote: 'Nota del punto (ej.: cortar aquí)',
  processing: 'Preparando foto…',
  uploading: 'Subiendo fotos…',
  retry: 'Reintentar',
  heic: 'Este navegador no puede abrir fotos HEIC. Tome la foto con la cámara o elija JPG/PNG.',
  decode: 'No se pudo leer la imagen.',
  tooLarge: 'La imagen supera 15 MB.',
  notImage: 'El archivo no es una imagen.',
  disclaimer: 'La referencia muestra un deseo estético; no es una recomendación técnica.',
  desiredResult: 'Resultado deseado',
  instructions: 'Instrucciones del cliente',
  plant: 'Planta',
  location: 'Ubicación',
  lastWork: 'Últimas intervenciones',
  assessTitle: 'Evaluación del resultado solicitado',
  assessComment: 'Comentario profesional',
  viable: 'Viable', partial: 'Parcialmente viable', not_recommended: 'No recomendado', inspect_first: 'Necesito inspeccionarla primero',
  saveAssessment: 'Guardar evaluación',
  askClarify: 'Pedir aclaración',
  clarifyPh: '¿Qué necesita aclarar el cliente?',
  proposeTitle: 'Proponer resultado acordado',
  exact: 'Exactamente la referencia', approximate: 'Aproximación razonable', modified: 'Modificado por recomendación profesional',
  scopePh: 'Describa lo que se hará y hasta dónde.',
  propose: 'Proponer alcance',
  agreeTitle: 'Resultado acordado',
  agree: 'Aceptar alcance',
  clientRequested: 'Lo que pidió el cliente',
  proRecommended: 'Lo que recomendó el profesional',
  agreed: 'Lo que se acordó',
  complete: 'Completar tarea con foto final',
  reviewTitle: '¿Se parece al resultado acordado?',
  yes: 'Sí', partialMatch: 'Parcialmente', no: 'No',
  approve: 'Aprobar resultado',
  adjust: 'Reportar ajuste necesario',
  feedbackPh: 'Comentario (obligatorio si pide un ajuste)',
  timeline: 'Historial del servicio',
  submit: 'Enviar al profesional',
  resubmit: 'Enviar aclaración',
  visualHistory: 'Servicios visuales',
  noHistory: 'Aún no hay servicios con resultado deseado para esta planta.',
  waitingAgreement: 'Esta tarea tiene un resultado deseado sin alcance acordado. Acuerde el alcance antes de completarla.',
  status: {
    draft: 'Borrador', client_submitted: 'Enviado', professional_review: 'En revisión profesional',
    needs_clarification: 'Requiere aclaración', professionally_validated: 'Evaluado',
    scope_agreed: 'Alcance acordado', result_submitted: 'Resultado entregado',
    client_approved: 'Aprobado', adjustment_requested: 'Ajuste solicitado',
  },
  events: {
    brief_created: 'Solicitud creada', reference_added: 'Foto agregada', reference_removed_before_submission: 'Foto retirada antes del envío',
    client_submitted: 'Enviado por el cliente', professional_review_started: 'Revisión profesional iniciada',
    clarification_requested: 'Aclaración solicitada', professional_assessed: 'Evaluación profesional',
    scope_proposed: 'Alcance propuesto', scope_agreed: 'Alcance acordado', result_submitted: 'Resultado final entregado',
    client_approved: 'Resultado aprobado', adjustment_requested: 'Ajuste solicitado',
  } as Record<string, string>,
};
type Copy = typeof es;

const en: Copy = {
  ...es,
  sectionTitle: 'How would you like it to look?', sectionHint: 'Optional. Show the current state and the result you expect.',
  serviceType: 'Service type', current: 'Current state', reference: 'Result reference',
  referenceHint: 'Upload a photo showing roughly how you want it to look.', agreedRef: 'Agreed reference', final: 'Final result',
  whatChange: 'What would you like to change?', whatChangePh: 'E.g. reduce height by about 30% and keep the bottom full.',
  takePhoto: 'Take or upload photo', fromHistory: 'Use a photo from a previous service', addPin: 'Tap the photo to mark a point',
  pinNote: 'Point note (e.g. cut here)', processing: 'Preparing photo…', uploading: 'Uploading photos…', retry: 'Retry',
  heic: 'This browser cannot open HEIC photos. Use the camera or choose JPG/PNG.', decode: 'The image could not be read.',
  tooLarge: 'The image is larger than 15 MB.', notImage: 'The file is not an image.',
  disclaimer: 'The reference shows an aesthetic wish; it is not a technical recommendation.',
  desiredResult: 'Desired result', instructions: 'Client instructions', plant: 'Plant', location: 'Location', lastWork: 'Recent work',
  assessTitle: 'Assessment of the requested result', assessComment: 'Professional comment',
  viable: 'Viable', partial: 'Partially viable', not_recommended: 'Not recommended', inspect_first: 'I need to inspect it first',
  saveAssessment: 'Save assessment', askClarify: 'Ask for clarification', clarifyPh: 'What should the client clarify?',
  proposeTitle: 'Propose the agreed result', exact: 'Exactly the reference', approximate: 'Reasonable approximation', modified: 'Modified after professional advice',
  scopePh: 'Describe what will be done and how far.', propose: 'Propose scope', agreeTitle: 'Agreed result', agree: 'Accept scope',
  clientRequested: 'What the client asked for', proRecommended: 'What the professional recommended', agreed: 'What was agreed',
  complete: 'Complete task with final photo', reviewTitle: 'Does it match the agreed result?', yes: 'Yes', partialMatch: 'Partially', no: 'No',
  approve: 'Approve result', adjust: 'Report needed adjustment', feedbackPh: 'Comment (required when requesting an adjustment)',
  timeline: 'Service history', submit: 'Send to professional', resubmit: 'Send clarification', visualHistory: 'Visual services',
  noHistory: 'No services with a desired result for this plant yet.',
  waitingAgreement: 'This task has a desired result without an agreed scope. Agree on the scope before completing it.',
  status: { draft: 'Draft', client_submitted: 'Submitted', professional_review: 'Professional review', needs_clarification: 'Needs clarification', professionally_validated: 'Assessed', scope_agreed: 'Scope agreed', result_submitted: 'Result delivered', client_approved: 'Approved', adjustment_requested: 'Adjustment requested' },
  events: { brief_created: 'Request created', reference_added: 'Photo added', reference_removed_before_submission: 'Photo removed before submission', client_submitted: 'Submitted by client', professional_review_started: 'Professional review started', clarification_requested: 'Clarification requested', professional_assessed: 'Professional assessment', scope_proposed: 'Scope proposed', scope_agreed: 'Scope agreed', result_submitted: 'Final result delivered', client_approved: 'Result approved', adjustment_requested: 'Adjustment requested' },
};

const de: Copy = {
  ...en,
  sectionTitle: 'Wie soll es aussehen?', sectionHint: 'Optional. Zeigen Sie den aktuellen Zustand und das gewünschte Ergebnis.',
  serviceType: 'Leistungsart', current: 'Aktueller Zustand', reference: 'Referenz für das Ergebnis',
  referenceHint: 'Laden Sie ein Foto hoch, das ungefähr zeigt, wie es aussehen soll.', agreedRef: 'Vereinbarte Referenz', final: 'Endergebnis',
  whatChange: 'Was möchten Sie ändern?', takePhoto: 'Foto aufnehmen oder hochladen', fromHistory: 'Foto eines früheren Einsatzes verwenden',
  disclaimer: 'Die Referenz zeigt einen ästhetischen Wunsch, keine fachliche Empfehlung.', desiredResult: 'Gewünschtes Ergebnis',
  assessTitle: 'Bewertung des gewünschten Ergebnisses', viable: 'Machbar', partial: 'Teilweise machbar', not_recommended: 'Nicht empfohlen', inspect_first: 'Erst vor Ort prüfen',
  saveAssessment: 'Bewertung speichern', agree: 'Umfang akzeptieren', approve: 'Ergebnis freigeben', adjust: 'Nachbesserung melden',
  submit: 'An Fachkraft senden', timeline: 'Verlauf', visualHistory: 'Visuelle Leistungen', complete: 'Aufgabe mit Endfoto abschließen',
  status: { draft: 'Entwurf', client_submitted: 'Gesendet', professional_review: 'In fachlicher Prüfung', needs_clarification: 'Rückfrage', professionally_validated: 'Bewertet', scope_agreed: 'Umfang vereinbart', result_submitted: 'Ergebnis geliefert', client_approved: 'Freigegeben', adjustment_requested: 'Nachbesserung angefragt' },
};

export function useVbCopy() {
  const { language } = useLanguage();
  const t = language === 'es' ? es : language === 'de' ? de : en;
  return { t, lang: language, es: language === 'es' };
}
